include "commons.conf"

fwkId=local

## mongodb
## -------
mongodb.host=localhost
mongodb.port=27017
mongodb.dbname=localvedantu
#mongodb.username=vikram
#mongodb.password="__REDACTED__"
## app user
## --------
app.defaultUsername="local@localhost.loc"


## web server
## ----------
app.host=localhost
applearn.host=localhost
learnapp.host=localhost
app.protocol=https
img.host="http://localhost:19080"
## hbase
## -----
hbase.zookeeper.quorum=localhost
hbase.zookeeper.property.clientPort=2181
hbase.tablepool.maxsize=20


## elasticsearch
## -------------
elasticsearch.cluster.name=elasticsearch
elasticsearch.transport.host=["127.0.0.1:9300"]
elasticsearch.refresh.time=1000


## Object storage and file system 
## ------------------------------
fs.class="com.vedantu.commons.fs.handlers.LocalFileSystemHandler"
#fs.class="com.vedantu.commons.fs.handlers.S3Handler"
util.temp_dir=/home/vedantu/data/temp
fs.local.basedir=/home/vedantu/data/temp/fs


## Messaging tables list
## -----------------------------
messages.message_table=message_table
messages.conversation_table=conversation_table
messages.user_message_table=user_message_table
messages.user_conversation_table=user_conversation_table

messages.message_table_v2=message_table_v2
messages.user_message_table_v2=user_message_table_v2

#email sender configs
smtp.host="127.0.0.1"

# email manager configurations
## email templates
email.configuration.enabled=yes


## end test config
## ~~~~~~~~~~~~~~~~~~
end.test.attempt.buffer=300000

#s3 bucket cors config
amazon.s3.bucket.allowedorigins=["*"]

email.vedantu.contact=""
#deployment domain for local doesnt really exist
deployment.domain="localhost"

#for url security cookies parsing
application.session.cookie="VEDANTU_LOCAL_SESSION"
environment.file.security.enabled=no
environment.file.direct.serving.enabled=no
check.referer.enabled=no

##Time Configuration for Doubts forum (in HOURS)
doubt.max.response.time=1
doubt.max.solution.time=12
doubt.exhaust.time=18

#Learnpedia Organization Id
#~~~~~~~~~~~~~~~~~~~~~~~
learnpedia.id=5715e87344aeb00d1c7fdbe8
