include "commons.conf"

fwkId="qa"

## mongodb
## -------
mongodb.host=localhost
mongodb.port=27017
mongodb.dbname=prodlp


## app user
## --------
app.defaultUsername="admin@learnpedia.in"


## web server
## ----------
app.host=qa.learnpedia.in
applearn.host=qa.learnpedia.in
learnapp.host=learnappqa.learnpedia.in
app.protocol=https
img.host="https://imgqa.learnpedia.in"

## hbase
## -----
hbase.zookeeper.quorum="apps.qa.learnpedia.in"
hbase.zookeeper.property.clientPort=2181
hbase.tablepool.maxsize=20


## elasticsearch
## -------------
elasticsearch.cluster.name=prodlp
elasticsearch.transport.host=["es.qa.learnpedia.in:9300"]
elasticsearch.refresh.time=1000


## Object storage and file system 
## ------------------------------
fs.class="com.vedantu.commons.fs.handlers.S3Handler"
#fs.class="com.vedantu.commons.fs.handlers.ObjectStorageHandler"
util.temp_dir=/home/ubuntu/data/temp
fs.local.basedir=/home/ubuntu/data/temp/fs


## Object storage authentication
## -----------------------------
objectstorage.username="SLOS221779-1:SL221779"
objectstorage.password="__REDACTED__"
objectstorage.baseurl="https://sng01.objectstorage.softlayer.net/auth/v1.0/"


## Message specific configurations
## -------------------------------
messages.message_table=message_table
messages.conversation_table=conversation_table
messages.user_message_table=user_message_table
messages.user_conversation_table=user_conversation_table

messages.message_table_v2=message_table_v2
messages.user_message_table_v2=user_message_table_v2

## Email sender config
## -------------------
#smtp.host="email-smtp.us-east-1.amazonaws.com"
#smtp.port=587
##smtp.ssl=
#smtp.tls=yes
#smtp.user="__AWS_ACCESS_KEY_REDACTED__"
#smtp.password="__REDACTED__"
#email.configuration.enabled=yes

smtp.host="smtp.gmail.com"
smtp.port=587
#smtp.ssl=
smtp.tls=yes
smtp.user="dm@learnpedia.in"
smtp.password="__REDACTED__"
email.configuration.enabled=yes

## end test config 
## ~~~~~~~~~~~~~~~~~~
end.test.attempt.buffer=300000


#s3 bucket cors config
amazon.s3.bucket.allowedorigins=["http://*.learnpedia.in","https://*.learnpedia.in"]
amazon.s3.accessKey="__REDACTED__"
amazon.s3.secretKey="__REDACTED__"
amazon.s3.bucket.identifier="uprep"

email.vedantu.contact="Learnpedia <test@learnpedia.in>"
deployment.domain="qa.learnpedia.in"

#for url security cookies parsing
application.session.cookie="LEARNPEDIA_QA_SESSION"
environment.file.security.enabled=yes
check.referer.enabled=yes

##Time Configuration for Doubts forum (in HOURS)
doubt.max.response.time=1
doubt.max.solution.time=12
doubt.exhaust.time=18

#Learnpedia Organization Id
#~~~~~~~~~~~~~~~~~~~~~~~
learnpedia.id=5551bf80e4b053fbc7baf90d
