include "application.conf"
include "email.conf"

application.log.file=/logger.xml

tnc.version=20131121
org.tnc.version=20131121
tnc.path=""
mime.types.file.path="../../commons/conf/MimeTypes"
media.types.file.path="../../commons/conf/MediaTypes"

#image sizes 
image.medium.width=600
image.medium.height=600
image.small.width=200
image.small.height=200
image.large.width=400
image.large.height=400
image.xsmall.width=100
image.xsmall.height=100

#Object storage authentication
## -----------------------------
objectstorage.username="<username>"
objectstorage.password="__REDACTED__"
objectstorage.baseurl="https://sng01.objectstorage.softlayer.net/auth/v1.0/"


#Amazon S3 authentication
## -----------------------------
amazon.s3.accessKey="__REDACTED__"
amazon.s3.secretKey="__REDACTED__"
amazon.s3.bucket.identifier="uprep"


#Configuration for automatic creation of org member
##-------------------------------
org.default.memberid.prefix="SYSGEN_"


#Configuration for test attempt upload to external organization server
##--------------------------------
org.ei.upload.attempt.batch.size=10
org.ei.upload.attempt.request.timeout=60
org.ei.upload.attempt.retry.interval=300000
org.ei.upload.attempt.retry.count=3


features.set=["ORGANIZATION CREATION","ILE"]

logo.url.itunes="https://play.google.com/store/apps/details?id=com.learnpedia.android"
logo.url.google_play="https://play.google.com/store/apps/details?id=com.learnpedia.android"
logo.url.windows_phone="https://play.google.com/store/apps/details?id=com.learnpedia.android"
logo.url.windows8="https://play.google.com/store/apps/details?id=com.learnpedia.android"
logo.url.blackberry="https://play.google.com/store/apps/details?id=com.learnpedia.android"


