email.postemail.sleep.time.milliseconds=200
email.template.sender="noreply@learnpedia.in"

email.endpoint.verification="verifyEmail"
email.endpoint.forgotpassword="__REDACTED__"
email.template.mock="mock"
email.template.emailAccessCode="emailAccessCode"
email.template.forgotpassword="__REDACTED__"
email.template.emailVerification="emailVerification"

## features email ##
##~~~~~~~~~~~~~~~~~~~~~~
email.template.feature="feature"

## notification email ##
#~~~~~~~~~~~~~~~~~~~~~~~
email.template.enabled.etypes=[]
email.template.enabled.etypes=["VOTE_ENTITY","ATTEMPT_ENTITY","MADE_VISIBLE","POST_REMARK","ADD_SOLUTION","ADD_COMMENT","INDEX_CHALLENGE","END_CHALLENGE"]
email.template.message="message"
email.template.voteNotification="voteNotification"
email.template.commentNotification="commentNotification"
email.template.attemptNotification="attemptNotification"
email.template.addSolutionNotification="addSolutionNotification"
email.template.endChallengeNotification="endChallengeNotification"
email.template.madeVisibleNotification="madeVisibleNotification"
email.template.remarks="remarks"
email.template.addChallengeNotification="addChallengeNotification"
email.template.signupWithAccessCode="signupWithAccessCode"
email.template.addorg="addorg"
email.template.approveorg="approveorg"
email.template.emailTemplate="emailTemplate"
email.template.emailtostudents="emailtostudents"
