#microsite configuration

microsite.base.pics.count=3
microsite.base.pics.list=[]
microsite.base.label.private.name=private
microsite.base.label.private.show=yes
microsite.base.label.public.name=public
microsite.base.privacy.policy=
microsite.base.google.play=
