remote.host.url=https://cmds.learnpedia.in
remote.host.router=extCMDSUploadAppRouter
desktop.app.id=DesktopApp
desktop.app.folder.name=Desktop App
desktop.storage.location=/home/ec2-user/data/deskAppData/fs
