#spring.data.mongodb.host=localhost
spring.data.mongodb.host=3.7.93.20
spring.data.mongodb.port=27017
spring.data.mongodb.database=prodlp
server.port=8090
spring.servlet.multipart.max-file-size=256MB
spring.servlet.multipart.max-request-size=256MB
spring.servlet.multipart.enabled=true
include="commons.qa.conf"
http.port=19012
jvm.memory="-Xms64M -Xmx128M"
application.mode=" ";
#REFERRAL CAMPAIGN CONFIG
#~~~~~~~~~~~~~~~~~~~~~~~~
campaign.referral=""
campaign.section.id=""
campaign.center.id=""
campaign.program.id=""
campaign.agent.packagedays=30
campaign.user.packagedays=14
#SMS COUNTRY CONFIG
#~~~~~~~~~~~~~~~~~~~~~~~
smscountry.url="http://api.smscountry.com/SMSCwebservice_bulk.aspx"
smscountry.user="learnpedia"
smscountry.passwd="__REDACTED__"
smscountry.sid="LPEDIA"
smscountry.mtype="N"
smscountry.dr="Y"
otp.size=4
#Learnpedia Organisation Id
#~~~~~~~~~~~~~~~~~~~~~~~~
learnpedia.id="5551bf80e4b053fbc7baf90d"
#Auto Add Demo Programs
#~~~~~~~~~~~~~~~~~~~~~~~
jeedemo.section.id=58649d4be4b0e84200e1c5b5
jeedemo.center.id=5576a97ae4b0a2060aa28bae
jeedemo.program.id=58649d27e4b0e84200e1c5b2
neetdemo.section.id=56bda1ace4b08963b7757389
neetdemo.center.id=5551f8d7e4b053fbc7baf922
neetdemo.program.id=56bda199e4b08963b7757386
#Programs Bucket Name
#~~~~~~~~~~~~~~~~~~~~~~
bucket.name=organization-qa-uprep
#Leadsquared Campaign Programs
#~~~~~~~~~~~~~~~~~~~~~~~
emp.section.id=595511dce4b06960ef7e19df
emp.center.id=5551f8d7e4b053fbc7baf922
emp.program.id=595511a6e4b06960ef7e19db
jeesoln.section.id="595511cae4b06960ef7e19dd"
jeesoln.center.id="5551f8d7e4b053fbc7baf922"
jeesoln.program.id="595511a6e4b06960ef7e19db"
neetseries.section.id="595511fee4b06960ef7e19e1"
neetseries.center.id="5551f8d7e4b053fbc7baf922"
neetseries.program.id="595511a6e4b06960ef7e19db"
#Programs custom description
#~~~~~~~~~~~~~~~~~~~~~~~
"55727779e4b0a2060aa28ab7.desc"="SCORE (Simple and Complete Online Resource) is a digital learning platform for various competitive exams"
"55727779e4b0a2060aa28ab7.firstPoint"="Videos - 4000+"
"55727779e4b0a2060aa28ab7.secondPoint"="Practice Content - 20000+"
"55727779e4b0a2060aa28ab7.thirdPoint"="Practice Mock Tests - 1800+"
"55727779e4b0a2060aa28ab7.fourthPoint"="Doubts Forum"
"55727779e4b0a2060aa28ab7.imageUrl"="/public/images/programImages/scoreneet_online.jpg"
"557ff3efe4b0b743a7561e3a.desc"="SCORE (Simple and Complete Online Resource) is a digital learning platform for various competitive exams"
"557ff3efe4b0b743a7561e3a.firstPoint"="Videos - 4000+"
"557ff3efe4b0b743a7561e3a.secondPoint"="Practice Content - 20000+"
"557ff3efe4b0b743a7561e3a.thirdPoint"="Practice Mock Tests - 1800+"
"557ff3efe4b0b743a7561e3a.fourthPoint"="Doubts Forum"
"557ff3efe4b0b743a7561e3a.imageUrl"="/public/images/programImages/scorejee_online.jpg"
"55929516e4b0d4df2b2ee799.desc"="SCORE (Simple and Complete Online Resource) is a digital learning platform for various competitive exams"
"55929516e4b0d4df2b2ee799.firstPoint"="Videos - 4000+"
"55929516e4b0d4df2b2ee799.secondPoint"="Practice Content - 20000+"
"55929516e4b0d4df2b2ee799.thirdPoint"="Practice Mock Tests - 1800+"
"55929516e4b0d4df2b2ee799.fourthPoint"="Doubts Forum"
"55929516e4b0d4df2b2ee799.imageUrl"="/public/images/programImages/scoreneet_online.jpg"
"584553b8e4b0ebfbb13653af.desc"="SCORE (Simple and Complete Online Resource) is a digital learning platform for various competitive exams"
"584553b8e4b0ebfbb13653af.firstPoint"="Videos - 4000+"
"584553b8e4b0ebfbb13653af.secondPoint"="Practice Content - 20000+"
"584553b8e4b0ebfbb13653af.thirdPoint"="Practice Mock Tests - 1800+"
"584553b8e4b0ebfbb13653af.fourthPoint"="Doubts Forum"
"584553b8e4b0ebfbb13653af.imageUrl"="/public/images/programImages/scorejee_sdcard.jpg"
"557bc3ffe4b0a2060aa28e27.desc"="SCORE (Simple and Complete Online Resource) is a digital learning platform for various competitive exams"
"557bc3ffe4b0a2060aa28e27.firstPoint"="Videos - 4000+"
"557bc3ffe4b0a2060aa28e27.secondPoint"="Practice Content - 20000+"
"557bc3ffe4b0a2060aa28e27.thirdPoint"="Practice Mock Tests - 1800+"
"557bc3ffe4b0a2060aa28e27.fourthPoint"="Doubts Forum"
"557bc3ffe4b0a2060aa28e27.imageUrl"="/public/images/programImages/scoreneet_sdcard.jpg"
"5551f925e4b053fbc7baf926.desc"="SCORE (Simple and Complete Online Resource) is a digital learning platform for various competitive exams"
"5551f925e4b053fbc7baf926.firstPoint"="Videos - 4000+"
"5551f925e4b053fbc7baf926.secondPoint"="Practice Content - 20000+"
"5551f925e4b053fbc7baf926.thirdPoint"="Practice Mock Tests - 1800+"
"5551f925e4b053fbc7baf926.fourthPoint"="Doubts Forum"
"5551f925e4b053fbc7baf926.imageUrl"="/public/images/programImages/scorejee_online.jpg"
"5575526de4b0a2060aa28b22.desc"="SCORE (Simple and Complete Online Resource) is a digital learning platform for various competitive exams"
"5575526de4b0a2060aa28b22.firstPoint"="Videos - 4000+"
"5575526de4b0a2060aa28b22.secondPoint"="Practice Content - 20000+"
"5575526de4b0a2060aa28b22.thirdPoint"="Practice Mock Tests - 1800+"
"5575526de4b0a2060aa28b22.fourthPoint"="Doubts Forum"
"5575526de4b0a2060aa28b22.imageUrl"="/public/images/programImages/scorejee_test.jpg"
"58649d4be4b0e84200e1c5b5.desc"="SCORE (Simple and Complete Online Resource) is a digital learning platform for various competitive exams"
"58649d4be4b0e84200e1c5b5.firstPoint"="Videos - 4000+"
"58649d4be4b0e84200e1c5b5.secondPoint"="Practice Content - 20000+"
"58649d4be4b0e84200e1c5b5.thirdPoint"="Practice Mock Tests - 1800+"
"58649d4be4b0e84200e1c5b5.fourthPoint"="Doubts Forum"
"58649d4be4b0e84200e1c5b5.imageUrl"="/public/images/programImages/scorejee_sdcard.jpg"
"56fcc8b2e4b060593b649b85.desc"="SCORE (Simple and Complete Online Resource) is a digital learning platform for various competitive exams"
"56fcc8b2e4b060593b649b85.firstPoint"="Videos - 4000+"
"56fcc8b2e4b060593b649b85.secondPoint"="Practice Content - 20000+"
"56fcc8b2e4b060593b649b85.thirdPoint"="Practice Mock Tests - 1800+"
"56fcc8b2e4b060593b649b85.fourthPoint"="Doubts Forum"
"56fcc8b2e4b060593b649b85.imageUrl"="/public/images/programImages/scorejee_test.jpg"
#InstaMojo key credentails
#~~~~~~~~~~~~~~~~~~~~~~~
instamojo.env=test
instamojo.url=https://test.instamojo.com/oauth2/token/
instamojo.clientid=test_jow34m9BKuNnhHcS2wJQ87W16cZBnRUf5hc
instamojo.clientsecretkey="__REDACTED__"
application.log.file=/logger.xml
tnc.version=20131121
org.tnc.version=20131121
tnc.path=""
mime.types.file.path="../../commons/conf/MimeTypes"
media.types.file.path="../../commons/conf/MediaTypes"
#image sizes
image.medium.width=600
image.medium.height=600
image.small.width=200
image.small.height=200
image.large.width=400
image.large.height=400
image.xsmall.width=100
image.xsmall.height=100
#Object storage authentication
## -----------------------------
objectstorage.username="<username>"
objectstorage.password="__REDACTED__"
objectstorage.baseurl="https://sng01.objectstorage.softlayer.net/auth/v1.0/"
#Configuration for automatic creation of org member
##-------------------------------
org.default.memberid.prefix=SYSGEN_
google.playstore.base.url=" "
#Configuration for test attempt upload to external organization server
##--------------------------------
org.ei.upload.attempt.batch.size=10
org.ei.upload.attempt.request.timeout=60
org.ei.upload.attempt.retry.interval=300000
org.ei.upload.attempt.retry.count=3
features.set=["ORGANIZATION CREATION","ILE"]
logo.url.itunes="https://play.google.com/store/apps/details?id=com.learnpedia.android"
logo.url.google_play="https://play.google.com/store/apps/details?id=com.learnpedia.android"
logo.url.windows_phone="https://play.google.com/store/apps/details?id=com.learnpedia.android"
logo.url.windows8="https://play.google.com/store/apps/details?id=com.learnpedia.android"
logo.url.blackberry="https://play.google.com/store/apps/details?id=com.learnpedia.android"
fwkId=qa
## mongodb
## -------
mongodb.host=localhost
mongodb.port=27017
mongodb.dbname=prodlp
## app user
## --------
app.defaultUsername="admin@learnpedia.in"
## web server
## ----------
app.host=qa.learnpedia.in
applearn.host=qa.learnpedia.in
learnapp.host=learnappqa.learnpedia.in
app.protocol=https
img.host="https://imgqa.learnpedia.in"
## hbase
## -----
hbase.zookeeper.quorum="apps.qa.learnpedia.in"
hbase.zookeeper.property.clientPort=2181
hbase.tablepool.maxsize=20
## elasticsearch
## -------------
elasticsearch.cluster.name=prodlp
elasticsearch.transport.host=["es.qa.learnpedia.in:9300"]
elasticsearch.refresh.time=1000
## Object storage and file system
## ------------------------------
fs.class=S3Handler
#fs.class="com.vedantu.commons.fs.handlers.ObjectStorageHandler"
util.temp_dir=/home/ubuntu/learnpedia/temp/
fs.local.basedir=/home/ubuntu/learnpedia/temp/fs
## Message specific configurations
## -------------------------------
messages.message_table=message_table
messages.conversation_table=conversation_table
messages.user_message_table=user_message_table
messages.user_conversation_table=user_conversation_table
messages.message_table_v2=message_table_v2
messages.user_message_table_v2=user_message_table_v2
## Email sender config
## -------------------
#smtp.host="email-smtp.us-east-1.amazonaws.com"
#smtp.port=587
##smtp.ssl=
#smtp.tls=yes
#smtp.user="__AWS_ACCESS_KEY_REDACTED__"
#smtp.password="__REDACTED__"
#email.configuration.enabled=yes
smtp.host="smtp.gmail.com"
smtp.port=587
#smtp.ssl=
smtp.tls=yes
smtp.user="dm@learnpedia.in"
smtp.password="__REDACTED__"
email.configuration.enabled=yes
## end test config
## ~~~~~~~~~~~~~~~~~~
end.test.attempt.buffer=300000
#s3 bucket cors config
amazon.s3.bucket.allowedorigins=["http://*.learnpedia.in","https://*.learnpedia.in"]
amazon.s3.accessKey="__REDACTED__"
amazon.s3.secretKey="__REDACTED__"
amazon.s3.bucket.identifier=uprep
email.vedantu.contact="Learnpedia <test@learnpedia.in>"
deployment.domain="qa.learnpedia.in"
#for url security cookies parsing
application.session.cookie="LEARNPEDIA_QA_SESSION"
environment.file.security.enabled=yes
check.referer.enabled=yes
##Time Configuration for Doubts forum (in HOURS)
doubt.max.response.time=1
doubt.max.solution.time=12
doubt.exhaust.time=18
#Learnpedia Organization Id
#~~~~~~~~~~~~~~~~~~~~~~~


