include "commons.conf"

fwkId="dev"

## mongodb
## -------
mongodb.host=mongo.dev.vedantu.com
mongodb.port=27017
mongodb.dbname=devvedantu


## app user
## --------
app.defaultUsername="admin@vedantu.com"


## web server
## ----------
app.host=dev.vedantu.com
app.protocol=https
img.host="https://imgdev.vedantu.com"

## hbase
## -----
hbase.zookeeper.quorum=localhost
hbase.zookeeper.property.clientPort=2181
hbase.tablepool.maxsize=20


## elasticsearch
## -------------
elasticsearch.cluster.name=devvedantu
elasticsearch.transport.host=["es.dev.vedantu.com:9300"]
elasticsearch.refresh.time=1000


## Object storage and file system 
## ------------------------------
fs.class="com.vedantu.commons.fs.handlers.S3Handler"
#fs.class="com.vedantu.commons.fs.handlers.ObjectStorageHandler"
util.temp_dir=/home/ubuntu/data/temp
fs.local.basedir=/home/ubuntu/data/temp/fs


## Object storage authentication
## -----------------------------
objectstorage.username="SLOS221779-1:SL221779"
objectstorage.password="__REDACTED__"
objectstorage.baseurl="https://sng01.objectstorage.softlayer.net/auth/v1.0/"


## Message specific configurations
## -------------------------------
messages.message_table=message_table
messages.conversation_table=conversation_table
messages.user_message_table=user_message_table
messages.user_conversation_table=user_conversation_table


## Email sender config
## -------------------
smtp.host="email-smtp.us-east-1.amazonaws.com"
smtp.port=25
#smtp.ssl=
smtp.tls=yes
smtp.user="__AWS_ACCESS_KEY_REDACTED__"
smtp.password="__REDACTED__"
email.configuration.enabled=yes

## end test config 
## ~~~~~~~~~~~~~~~~~~
end.test.attempt.buffer=300000


#s3 bucket cors config
amazon.s3.bucket.allowedorigins=["http://*.vedantu.com","https://*.vedantu.com"]

email.vedantu.contact="test@vedantu.com"
environment.file.security.enabled=yes
check.referer.enabled=yes
