include "commons.conf"

fwkId="prod"

## mongodb
## -------
mongodb.host=mongo.learnpedia.in
mongodb.port=27017
mongodb.dbname=prodlp


## app user
## --------
app.defaultUsername="admin@learnpedia.in"


## web server
## ----------
#app.host=learn.learnpedia.in
app.host=cmds.learnpedia.in
applearn.host=learn.learnpedia.in
learnapp.host=www.learnpedia.in
app.protocol=https
img.host="https://imglearn.learnpedia.in"

## hbase
## -----
hbase.zookeeper.quorum="hbase.learnpedia.in"
hbase.zookeeper.property.clientPort=2181
hbase.tablepool.maxsize=20


## elasticsearch
## -------------
elasticsearch.cluster.name=prodlp
elasticsearch.transport.host=["es.learnpedia.in:9300"]
elasticsearch.refresh.time=1000


## Object storage and file system 
## ------------------------------
fs.class="com.vedantu.commons.fs.handlers.S3Handler"
#fs.class="com.vedantu.commons.fs.handlers.LocalFileSystemHandler"
util.temp_dir=/home/ubuntu/data/temp
fs.local.basedir=/home/ubuntu/data/temp/fs


## Message specific configurations
## -------------------------------
messages.message_table=message_table
messages.conversation_table=conversation_table
messages.user_message_table=user_message_table
messages.user_conversation_table=user_conversation_table

messages.message_table_v2=message_table_v2
messages.user_message_table_v2=user_message_table_v2

## Email sender config
## -------------------
smtp.host="smtp.sendgrid.net"
smtp.port=587
#smtp.ssl=
smtp.tls=yes
smtp.user="apikey"
smtp.password="__REDACTED__"
email.configuration.enabled=yes

## end test config
## ~~~~~~~~~~~~~~~~~~
end.test.attempt.buffer=300000

#s3 bucket cors config
#amazon.s3.bucket.allowedorigins=["http://*.vedantu.com","https://*.vedantu.com"]
amazon.s3.bucket.allowedorigins=["http://*.learnpedia.in","https://*.learnpedia.in"]
deployment.domain="learn.learnpedia.in"
email.vedantu.contact="contact@learnpedia.in"

#for url security cookies parsing
application.session.cookie="LEARNPEDIA_PROD_SESSION"
environment.file.security.enabled=yes
check.referer.enabled=yes

##Time Configuration for Doubts forum (in HOURS)
doubt.max.response.time=1
doubt.max.solution.time=12
doubt.exhaust.time=18

#Learnpedia Organization Id
#~~~~~~~~~~~~~~~~~~~~~~~
learnpedia.id=5513a38de4b095b85aa162fd
