include "commons.local.conf"

http.port=19014
jvm.memory="-Xms64M -Xmx128M"

symbol.file="conf/resources/symbol_map.txt"

#Learnpedia Organization Id
#~~~~~~~~~~~~~~~~~~~~~~~
learnpedia.id="584e44e8c92e5dca741bae2a"