include "commons.prod.conf"

http.port=19014
jvm.memory="-Xms512M -Xmx3072M"

symbol.file="conf/resources/symbol_map.txt"

#Learnpedia Organization Id
#~~~~~~~~~~~~~~~~~~~~~~~
learnpedia.id="5513a38de4b095b85aa162fd"