include "commons.qa.conf"

http.port=19014
jvm.memory="-Xms64M -Xmx128M"

symbol.file="conf/resources/symbol_map.txt"

#Learnpedia Organization Id
#~~~~~~~~~~~~~~~~~~~~~~~
learnpedia.id="5551bf80e4b053fbc7baf90d"