include "commons.local.conf"

http.port=19017
jvm.memory="-Xms64M -Xmx128M"

vedantu.newsfeed.lookbackdays=50

newsfeeds.default.count=10
activityfeeds.default.count=10
notifications.default.count=10
