include "commons.prod.conf"

http.port=19017

jvm.memory="-Xms256M -Xmx512M"

vedantu.newsfeed.lookbackdays=100

newsfeeds.default.count=10
activityfeeds.default.count=10
notifications.default.count=10

