#spring.data.mongodb.host=localhost
spring.data.mongodb.host=3.7.93.20
spring.data.mongodb.port=27017
spring.data.mongodb.database=prodlp
server.port=8020
amazon.s3.bucket.allowedorigins=["http://*.learnpedia.in","https://*.learnpedia.in"]
amazon.s3.accessKey="__REDACTED__"
amazon.s3.secretKey="__REDACTED__"
amazon.s3.bucket.identifier=uprep
application.mode=""
img.host=""
fwkId=qa
fs.class=S3Handler
media.types.file.path=../../commons/conf/MediaTypes
learnpedia.id=5551bf80e4b053fbc7baf90d
application.session.cookie="VEDANTU_LOCAL_SESSION"
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
activityfeeds.default.count=10

