include "commons.prod.conf"

http.port=19022
jvm.memory="-Xms128M -Xmx256M"

payment.page.url="https://payments.learnpedia.in/paymentGateway.html"
payment.defaultChannel="INSTAMOJO"

ccavenue.charging.url="https://secure.ccavenue.com/transaction/transaction.do"
ccavenue.merchant_id="96494"
ccavenue.access_code="AVYQ64DD92BL85QYLB"
ccavenue.enc_key="6975C53ED38230FE408B5EA7F4507FAE"
ccavenue.redirect_url="https://payments.vedantu.com/payments/onPaymentReceived"

ebs.charging.url="https://secure.ebs.in/pg/ma/sale/pay/"
ebs.accountId="11744"
ebs.secretKey="__REDACTED__"
ebs.redirect_url="https://payments.learnpedia.in/payments/onPaymentReceivedEBS?DR={DR}"
ebs.mode="LIVE"
ebs.pageId=""
ebs.securehash.algorithm="MD5"

instamojo.charging.url="https://www.instamojo.com/api/1.1/payment-requests/"
instamojo.apikey="__REDACTED__"
instamojo.authtoken="52c1c79263eb5a5d4d849983046631f7"

targetPMT.orgId="5583d562e4b0f968650c79cc"
targetPMT.paymentChannel="EBS"
