include "commons.qa.conf"

http.port=19022
jvm.memory="-Xms64M -Xmx128M"

payment.page.url="https://qa.learnpedia.in/paymentGateway.html"
payment.defaultChannel="INSTAMOJO"

ccavenue.charging.url="https://secure.ccavenue.com/transaction/transaction.do"
ccavenue.merchant_id="96494"
ccavenue.access_code="AVYQ64DD92BL85QYLB"
ccavenue.enc_key="6975C53ED38230FE408B5EA7F4507FAE"
ccavenue.redirect_url="https://qa.learnpedia.in/payments/onPaymentReceived"

ebs.charging.url="https://secure.ebs.in/pg/ma/sale/pay/"
ebs.accountId="11744"
ebs.secretKey="__REDACTED__"
ebs.redirect_url="https://qa.learnpedia.in/payments/onPaymentReceivedEBS?DR={DR}"
ebs.mode="TEST"
ebs.pageId=""
ebs.securehash.algorithm="MD5"

instamojo.charging.url="https://test.instamojo.com/api/1.1/payment-requests/"
instamojo.apikey="__REDACTED__"
instamojo.authtoken="test_bf24b6355b88f4a5854eb7178fb"

targetPMT.orgId="5717466ce4b04ea72fe6e079"
targetPMT.paymentChannel="CCAvenue"
