package com.vedantu.organizations.auth;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Pattern;

import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.lang3.RandomStringUtils;
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.mutable.MutableBoolean;

import play.Logger;
import play.Logger.ALogger;
import play.Play;

import com.vedantu.billing.dao.SaleDetailsDAO;
import com.vedantu.billing.dao.TransactionDAO;
import com.vedantu.billing.enums.ItemCategory;
import com.vedantu.billing.managers.OrderManager;
import com.vedantu.billing.models.Order;
import com.vedantu.billing.models.SaleDetails;
import com.vedantu.billing.pojos.OrderItemDetails;
import com.vedantu.commons.VedantuErrorCode;
import com.vedantu.commons.VedantuException;
import com.vedantu.commons.enums.AuthType;
import com.vedantu.commons.enums.DeviceType;
import com.vedantu.commons.enums.EntityType;
import com.vedantu.commons.enums.EventType;
import com.vedantu.commons.pojos.InputFieldInfo;
import com.vedantu.commons.pojos.Interval;
import com.vedantu.commons.pojos.Location;
import com.vedantu.commons.pojos.SellableItemDetails;
import com.vedantu.commons.pojos.SrcEntity;
import com.vedantu.commons.utils.ObjectIdUtils;
import com.vedantu.commons.utils.VedantuStringUtils;
import com.vedantu.organization.daos.OrgMemberDAO;
import com.vedantu.organization.daos.OrgSectionDAO;
import com.vedantu.organization.daos.OrganizationDAO;
import com.vedantu.organization.enums.AccessScope;
import com.vedantu.organization.enums.OrgMemberProfile;
import com.vedantu.organization.enums.OrgMemberState;
import com.vedantu.organization.enums.RevenueModel;
import com.vedantu.organization.event.details.SignupWithAccessCodeEmailDetails;
import com.vedantu.organization.managers.CampaignCodeManager;
import com.vedantu.organization.managers.OrgMemberManager;
import com.vedantu.organization.models.OrgMember;
import com.vedantu.organization.models.OrgSection;
import com.vedantu.organization.models.Organization;
import com.vedantu.organization.pojos.OrgMemberExtraInfo;
import com.vedantu.organization.pojos.OrgMemberMappingInfo;
import com.vedantu.organization.pojos.requests.ApplyCampaignCodeReq;
import com.vedantu.organization.pojos.requests.members.AddOrgMemberMappingReq;
import com.vedantu.organization.pojos.requests.members.AddOrgMemberReq;
import com.vedantu.organization.pojos.responses.ApplyCampaignCodeRes;
import com.vedantu.organization.pojos.responses.members.AddOrgMemberMappingRes;
import com.vedantu.organization.pojos.responses.members.AddOrgMemberRes;
import com.vedantu.user.daos.UserDAO;
import com.vedantu.user.managers.UserManager;
import com.vedantu.user.models.User;
import com.vedantu.user.pojos.UserEmailInfo;
import com.vedantu.user.pojos.UserExtendedInfo;
import com.vedantu.user.pojos.requests.AddUserReq;
import com.vedantu.user.pojos.responses.AddUserRes;
import com.vedantu.user.pojos.responses.UserAuthRes;

public abstract class AuthHandler {

    protected Organization       organization;
    public final AuthType        authType;
    private static final int     SYSTEM_GENERATED_PASS_LENGTH   = 6;
    private static final Pattern REGEX_SYSGEN_MEMBER_ID_PATTERN = Pattern
                                                                        .compile("^"
                                                                                + getAutogeneratedMemeberIdKeyPrefix()
                                                                                + "[0-9]*");
    private static final ALogger LOGGER                         = Logger.of(AuthHandler.class);
    private static final int     DEFAULT_CAMPAIGN_PACKAGE_DAYS  = 365;

    private static final String  CAMPAIGN_REFERRAL_CODE              = Play.application()
                                                                           .configuration()
                                                                           .getString("campaign.referral");

    public AuthHandler(Organization org, AuthType authType) {

        this.organization = org;
        this.authType = authType;

    }

    protected OrgMember checkOrgMember(String memberId, String orgId) throws VedantuException {

        OrgMember orgMember = OrgMemberDAO.INSTANCE.getMemberByMemberId(orgId, memberId);

        if (null == orgMember) {
            throw new VedantuException(VedantuErrorCode.ORGANIZATION_MEMBER_NOT_FOUND);

        }

        long currentTime = new Date().getTime();

        if (orgMember._getMemberState(currentTime) == OrgMemberState.BLOCKED) {
            throw new VedantuException(VedantuErrorCode.MEMBER_IS_BLOCKED);
        }
        return orgMember;

    }

    protected AddOrgMemberRes addOrgMember(AddOrgMemberReq addOrgMemberReq,
            boolean isMemberIdSysGenerated) throws VedantuException {

        if (!VedantuStringUtils.isValidDOB(addOrgMemberReq.dob)) {
            throw new VedantuException(VedantuErrorCode.INVALID_DATE_FORMAT);
        }

        if (!VedantuStringUtils.isValidContactNumber(addOrgMemberReq.contactNumber)) {
            throw new VedantuException(VedantuErrorCode.INVALID_CONTACT_NUMBER);
        }

        if (StringUtils.isEmpty(addOrgMemberReq.getTargetMemberId())
                && StringUtils.isEmpty(addOrgMemberReq.getEmail()) && !addOrgMemberReq.isOTPsignup) {
            String msg = "memberId,email and contact number can not be empty";
            throw new VedantuException(VedantuErrorCode.ORGANIZATION_MISSING_MEMBER_ID_AND_EMAIL,
                    msg);
        }

        if (!isMemberIdSysGenerated
                && REGEX_SYSGEN_MEMBER_ID_PATTERN.matcher(addOrgMemberReq.getTargetMemberId())
                        .matches()) {
            LOGGER.error("system generated memberId[" + addOrgMemberReq.getTargetMemberId()
                    + "] pattern not allowed as input");
            throw new VedantuException(VedantuErrorCode.ORGANIZATION_MEMBER_ID_PATTERN_NOT_ALLOWED,
                    "system generated memberId[" + addOrgMemberReq.getTargetMemberId()
                            + "] pattern not allowed as input");
        }
        User user = null;
        OrgMember orgMember = StringUtils.isEmpty(addOrgMemberReq.getTargetMemberId()) ? null
                : OrgMemberDAO.INSTANCE.getMemberByMemberId(addOrgMemberReq.orgId,
                        addOrgMemberReq.getTargetMemberId());
        if (null != orgMember) {
            throw new VedantuException(VedantuErrorCode.ORGANIZATION_MEMBER_ALREADY_EXISTS);
        }
        if(StringUtils.isNotEmpty(addOrgMemberReq.getEmail()) && !addOrgMemberReq.getTargetMemberId().equals(OrgMemberDAO.SUPER_ADMIN_MEMBER_ID)){
            orgMember = OrgMemberDAO.INSTANCE.getOrgMemberWithEmail(addOrgMemberReq.orgId, addOrgMemberReq.getEmail());
            user = UserDAO.INSTANCE.getUserByEmail(addOrgMemberReq.getEmail());
        }
        if (null != orgMember || null != user) {
            throw new VedantuException(VedantuErrorCode.ORGANIZATION_MEMBER_ALREADY_EXISTS);
        }
        if(StringUtils.isNotEmpty(addOrgMemberReq.contactNumber) && !addOrgMemberReq.getTargetMemberId().equals(OrgMemberDAO.SUPER_ADMIN_MEMBER_ID)){
            orgMember = OrgMemberDAO.INSTANCE.getByUserPhone(addOrgMemberReq.contactNumber, addOrgMemberReq.countryCode);
            user = UserDAO.INSTANCE.findUser(addOrgMemberReq.countryCode+addOrgMemberReq.contactNumber);
        }
        if (null != orgMember || null != user) {
            throw new VedantuException(VedantuErrorCode.USER_ALREADY_EXISTS);
        }
        if(StringUtils.isNotEmpty(addOrgMemberReq.referrerCode)){
            if(!OrgMemberDAO.INSTANCE
                    .isValidReferralCode(addOrgMemberReq.referrerCode)){
                throw new VedantuException(VedantuErrorCode.INVALID_REFERER);
            }
        }



        Interval interval = new Interval();
        interval.setFrom(new Date().getTime());
        interval.setTill(-1);


        OrgMember member = null;
        String username = StringUtils.equals(OrgMemberDAO.SUPER_ADMIN_MEMBER_ID,
                addOrgMemberReq.getTargetMemberId())
                || addOrgMemberReq.useEmailAsUsername ? addOrgMemberReq.getEmail()
                : getMemberUsername(addOrgMemberReq.orgId, addOrgMemberReq.getTargetMemberId());
        if (null == addOrgMemberReq.countryCode || StringUtils.isEmpty(addOrgMemberReq.countryCode))
            addOrgMemberReq.countryCode = "91";
        if (StringUtils.isNotEmpty(username) && !addOrgMemberReq.usePhoneAsUsername) {
            user = UserDAO.INSTANCE.findUser(username);
        } else if (addOrgMemberReq.isOTPsignup) {
            member = OrgMemberDAO.INSTANCE.getByUserPhone(addOrgMemberReq.contactNumber,
                    addOrgMemberReq.countryCode);
            username = addOrgMemberReq.countryCode + addOrgMemberReq.contactNumber;
        }

        String userId = null;

        if (null == user && null == member) {
            LOGGER.debug("will add user for username: " + username);
            boolean isSignupWithAccessCode = StringUtils.isEmpty(addOrgMemberReq.password)
                    && addOrgMemberReq.useEmailAsUsername && addOrgMemberReq.usePhoneAsUsername;

            boolean isSysGenPassword = StringUtils.isEmpty(addOrgMemberReq.password) ? true : false;

            String password = StringUtils.isNotEmpty(addOrgMemberReq.password) ? addOrgMemberReq.password
                    : (addOrgMemberReq.useEmailAsUsername ? RandomStringUtils
                            .randomAlphanumeric(SYSTEM_GENERATED_PASS_LENGTH) : OrgMemberManager
                            .getMemberDefaultPassword(addOrgMemberReq.profile,
                                    addOrgMemberReq.getTargetMemberId(), addOrgMemberReq.dob));
            AddUserReq addUserReq = new AddUserReq(username, password, addOrgMemberReq.firstName,
                    addOrgMemberReq.lastName, addOrgMemberReq.dob, addOrgMemberReq.gender,
                    addOrgMemberReq.getEmail(),
                    StringUtils.isNotEmpty(addOrgMemberReq.extUserId) ? AuthType.EXT_AUTH_ORG
                            : AuthType.VEDANTU);
            addUserReq.twitterHandle = addOrgMemberReq.twitterHandle;
            addUserReq.orgId = organization._getStringId();
            addUserReq.isSysGenPassword = isSysGenPassword;
            if(addOrgMemberReq.isOTPsignup || addOrgMemberReq.isValidPhone){
                addUserReq.isPhoneVerified = true;
            }
            addUserReq.isOTPuser = addOrgMemberReq.isOTPsignup;
            addUserReq.callingAppId = addOrgMemberReq.callingAppId;
            AddUserRes addUserRes = UserManager.addUser(addUserReq);
            userId = addUserRes.id;

            if (isSignupWithAccessCode) {

                user = UserDAO.INSTANCE.getById(userId);
                SignupWithAccessCodeEmailDetails emailDetails;
                try {
                    emailDetails = new SignupWithAccessCodeEmailDetails();
                    emailDetails.user = new UserEmailInfo();
                    emailDetails.password = password;
                    emailDetails.userName = username;
                    emailDetails.user
                            .fromUserExtendedInfo((UserExtendedInfo) user.toExtendedInfo());
                    emailDetails.addRecepient(emailDetails.user.getFullName(),
                            user.emailChangeReq.email);
                    emailDetails.orgId = organization._getStringId();
                    OrgMemberManager.generateEventAysc(user._getStringId(), emailDetails,
                            EventType.SEND_INSTANT_EMAIL);
                } catch (ClassNotFoundException e) {
                    LOGGER.error("Run time class not found", e);
                }

            }

        } else {
            if (addOrgMemberReq.useEmailAsUsername) {
                throw new VedantuException(VedantuErrorCode.USER_ALREADY_EXISTS,
                        "a user is already created with email[" + addOrgMemberReq.getEmail() + "]");
            } else if (addOrgMemberReq.usePhoneAsUsername) {
                throw new VedantuException(VedantuErrorCode.USER_ALREADY_EXISTS,
                        "a user is already created with phone[" + addOrgMemberReq.contactNumber
                                + "]");
            }
            // TODO: Send notification before linking
            userId = user._getStringId();
        }

        if (OrgMemberProfile.STUDENT == addOrgMemberReq.profile) {
            orgMember = OrgMemberDAO.INSTANCE.addMember(addOrgMemberReq.orgId, userId,
                    addOrgMemberReq.getTargetMemberId(), addOrgMemberReq.firstName,
                    addOrgMemberReq.lastName, addOrgMemberReq.dob, addOrgMemberReq.gender,
                    addOrgMemberReq.getEmail(), addOrgMemberReq.profile,
                    addOrgMemberReq.contactNumber, addOrgMemberReq.countryCode,
                    addOrgMemberReq.father, addOrgMemberReq.mother, addOrgMemberReq.guardian,
                    addOrgMemberReq.getParentEmail(), interval, addOrgMemberReq.extUserId,
                    addOrgMemberReq.extraInfo, addOrgMemberReq.referrerCode);

        } else {
            orgMember = OrgMemberDAO.INSTANCE.addMember(addOrgMemberReq.orgId, userId,
                    addOrgMemberReq.getTargetMemberId(), addOrgMemberReq.firstName,
                    addOrgMemberReq.lastName, addOrgMemberReq.dob, addOrgMemberReq.gender,
                    addOrgMemberReq.getEmail(), addOrgMemberReq.profile,
                    addOrgMemberReq.contactNumber, addOrgMemberReq.countryCode, false, interval,
                    addOrgMemberReq.extUserId, addOrgMemberReq.extraInfo);
        }

        AddOrgMemberRes addOrgMemberRes = new AddOrgMemberRes(orgMember._getStringId(),
                orgMember.recordState, orgMember.orgId, orgMember.userId);
        addOrgMemberRes.orgMemberId = orgMember._getStringId();
        addOrgMemberRes.memberId = orgMember.memberId;
        addOrgMemberRes.firstName = orgMember.firstName;
        addOrgMemberRes.lastName = orgMember.lastName;
        addOrgMemberRes.thumbnail = orgMember._getThumbnailUrl();
        addOrgMemberRes.authType = authType;
        addOrgMemberRes.contactNumber = orgMember.contactNumber;

        UserDAO.INSTANCE.acceptTnC(orgMember.userId, true, UserManager.getLatestTnC());

        if (addOrgMemberReq.campaignCode != null && !addOrgMemberReq.campaignCode.equals("")) {
            LOGGER.info(":::::::       Applying campaign code       ::::::::::");
            ApplyCampaignCodeReq applyCampaignCodeReq = new ApplyCampaignCodeReq();
            applyCampaignCodeReq.campaignCode = addOrgMemberReq.campaignCode;
            applyCampaignCodeReq.userId = userId;
            ApplyCampaignCodeRes applyCampaignCodeRes = CampaignCodeManager
                    .applyCampaignCode(applyCampaignCodeReq);
            if (applyCampaignCodeRes.applied) {
                LOGGER.info("::::::::    Coupon Code Applied     :::::::");
                addOrgMemberRes.showSpecialMessage = true;
                LOGGER.info(":::: Initializing message    :::::");
                // This message should match the template of smCountry. You
                // can't change
                // the template here.
                String message = "Thank you for registering on Learnpedia! You can enjoy our JEE/NEET free demo. "
                        + "You will get Rs50 PayTM cash on your mobile number "
                        + orgMember.contactNumber + " within 7 days";
                String response = OrgMemberManager.sendOTP(orgMember.countryCode
                        + orgMember.contactNumber, message , orgMember.orgId);
                LOGGER.info("Response from smsCountry " + response);
            } else {
                LOGGER.info("::::::::    Coupon Code Not Applied     :::::::");
            }
        }

        Integer packageDays = StringUtils.isEmpty(addOrgMemberReq.referrerCode) ? 0 : checkCampaignReferral(addOrgMemberReq);
        if (packageDays != null && packageDays > 0) {
            AddOrgMemberMappingReq addOrgMemberMappingReq = new AddOrgMemberMappingReq();
            addOrgMemberMappingReq.orgId = orgMember.orgId;
            addOrgMemberMappingReq.targetProfile = orgMember.profile;
            addOrgMemberMappingReq.targetUserId = orgMember.userId;
            addOrgMemberMappingReq.targetOrgMemberId = orgMember._getStringId();
            List<String> sectionIds = new ArrayList<String>();
            sectionIds.add(Play.application().configuration().getString("campaign.section.id"));
            addOrgMemberMappingReq.programId = Play.application().configuration()
                    .getString("campaign.program.id");
            addOrgMemberMappingReq.centerId = Play.application().configuration()
                    .getString("campaign.center.id");
            addOrgMemberMappingReq.sectionIds = sectionIds;
            addOrgMemberMappingReq.packageDays = packageDays;
            addOrgMemberMapping(addOrgMemberMappingReq, true);
        }
        // Below code is to add demo programs for uprep students.
        String UPrepOrgId = "5df8a0d0e4b0897459b25d86";
        if(addOrgMemberReq.orgId.equals(UPrepOrgId)){
            if(addOrgMemberReq.extraInfo != null && !addOrgMemberReq.extraInfo.isEmpty()){
                for(OrgMemberExtraInfo extraInfo: addOrgMemberReq.extraInfo){
                    if(extraInfo.name.equalsIgnoreCase("program")){
                        if(extraInfo.value.equalsIgnoreCase("JEE")){
                            addOrgMemberReq.autoAddDemoProgram = true;
                            addOrgMemberReq.progType = "JEE";
                        }else if(extraInfo.value.equalsIgnoreCase("NEET")){
                            addOrgMemberReq.autoAddDemoProgram = true;
                            addOrgMemberReq.progType = "NEET";
                        }
                    }
                }
            }
        }

        if (addOrgMemberReq.autoAddDemoProgram) {
            AddOrgMemberMappingReq addOrgMemberMappingReq = new AddOrgMemberMappingReq();
            addOrgMemberMappingReq.orgId = orgMember.orgId;
            addOrgMemberMappingReq.targetProfile = orgMember.profile;
            addOrgMemberMappingReq.targetUserId = orgMember.userId;
            addOrgMemberMappingReq.targetOrgMemberId = orgMember._getStringId();
            boolean demoProgFound = false;
            List<String> sectionIds = new ArrayList<String>();
            if (StringUtils.containsIgnoreCase(addOrgMemberReq.progType, "JEE")) {
                demoProgFound = true;
                sectionIds.add(Play.application().configuration().getString("jeedemo.section.id"));
                addOrgMemberMappingReq.programId = Play.application().configuration()
                        .getString("jeedemo.program.id");
                addOrgMemberMappingReq.centerId = Play.application().configuration()
                        .getString("jeedemo.center.id");
            } else if (StringUtils.containsIgnoreCase(addOrgMemberReq.progType, "NEET")) {
                demoProgFound = true;
                sectionIds.add(Play.application().configuration().getString("neetdemo.section.id"));
                addOrgMemberMappingReq.programId = Play.application().configuration()
                        .getString("neetdemo.program.id");
                addOrgMemberMappingReq.centerId = Play.application().configuration()
                        .getString("neetdemo.center.id");
            }

            if (demoProgFound) {
                addOrgMemberMappingReq.sectionIds = sectionIds;
                checkIfAddMappingAllowed(addOrgMemberMappingReq);
                addOrgMemberMapping(addOrgMemberMappingReq, true);
                addOrgMemberRes.autoAddDemoProgram = true;
            } else {
                LOGGER.error("::::::      Could not get correct program to auto add demo program        ::::::::");
            }
        }

        // Add Leadsquared Campaign program if required.
        if (addOrgMemberReq.autoAddCampaignProgram) {
            AddOrgMemberMappingReq addOrgMemberMappingReq = new AddOrgMemberMappingReq();
            addOrgMemberMappingReq.orgId = orgMember.orgId;
            addOrgMemberMappingReq.targetProfile = orgMember.profile;
            addOrgMemberMappingReq.targetUserId = orgMember.userId;
            addOrgMemberMappingReq.targetOrgMemberId = orgMember._getStringId();
            boolean campaignProgFound = false;
            List<String> sectionIds = new ArrayList<String>();
            if (StringUtils.equalsIgnoreCase(addOrgMemberReq.campaignAddProgram, "emp")) {
                campaignProgFound = true;
                sectionIds.add(Play.application().configuration().getString("emp.section.id"));
                addOrgMemberMappingReq.programId = Play.application().configuration()
                        .getString("emp.program.id");
                addOrgMemberMappingReq.centerId = Play.application().configuration()
                        .getString("emp.center.id");
            } else if (StringUtils.equalsIgnoreCase(addOrgMemberReq.campaignAddProgram, "jeesoln")) {
                campaignProgFound = true;
                sectionIds.add(Play.application().configuration().getString("jeesoln.section.id"));
                addOrgMemberMappingReq.programId = Play.application().configuration()
                        .getString("jeesoln.program.id");
                addOrgMemberMappingReq.centerId = Play.application().configuration()
                        .getString("jeesoln.center.id");
            } else if (StringUtils.equalsIgnoreCase(addOrgMemberReq.campaignAddProgram,
                    "neetseries")) {
                campaignProgFound = true;
                sectionIds.add(Play.application().configuration()
                        .getString("neetseries.section.id"));
                addOrgMemberMappingReq.programId = Play.application().configuration()
                        .getString("neetseries.program.id");
                addOrgMemberMappingReq.centerId = Play.application().configuration()
                        .getString("neetseries.center.id");
            } else if (StringUtils.equalsIgnoreCase(addOrgMemberReq.campaignAddProgram, "jeedemo")
                    || StringUtils.equalsIgnoreCase(addOrgMemberReq.campaignAddProgram, "jee")) {
                campaignProgFound = true;
                sectionIds.add(Play.application().configuration().getString("jeedemo.section.id"));
                addOrgMemberMappingReq.programId = Play.application().configuration()
                        .getString("jeedemo.program.id");
                addOrgMemberMappingReq.centerId = Play.application().configuration()
                        .getString("jeedemo.center.id");
            } else if (StringUtils.equalsIgnoreCase(addOrgMemberReq.campaignAddProgram, "neetdemo")
                    || StringUtils.equalsIgnoreCase(addOrgMemberReq.campaignAddProgram, "neet")) {
                campaignProgFound = true;
                sectionIds.add(Play.application().configuration().getString("neetdemo.section.id"));
                addOrgMemberMappingReq.programId = Play.application().configuration()
                        .getString("neetdemo.program.id");
                addOrgMemberMappingReq.centerId = Play.application().configuration()
                        .getString("neetdemo.center.id");
            }

            if (campaignProgFound) {
                addOrgMemberMappingReq.sectionIds = sectionIds;
                addOrgMemberMappingReq.packageDays = DEFAULT_CAMPAIGN_PACKAGE_DAYS;
                checkIfAddMappingAllowed(addOrgMemberMappingReq);
                addOrgMemberMapping(addOrgMemberMappingReq, true);
                addOrgMemberRes.autoAddCampaignProgram = true;
            } else {
                LOGGER.error("::::::      Could not find campaign program to auto add        ::::::::");
            }

        }



        return addOrgMemberRes;
    }

    private Integer checkCampaignReferral(AddOrgMemberReq addOrgMemberReq) {
        LOGGER.debug("Referrer Code is: " + addOrgMemberReq.referrerCode);
        OrgMember orgMember = OrgMemberDAO.INSTANCE.getOrgMemberFromReferralCode(addOrgMemberReq.referrerCode);
        Integer packageDays = Integer.valueOf(0);
		if (orgMember == null) {
			return packageDays;
		}
        if(StringUtils.equals(CAMPAIGN_REFERRAL_CODE, orgMember.referrerUserId)) {
            packageDays = Play.application().configuration().getInt("campaign.user.packagedays");
        }
        else if(StringUtils.equals(CAMPAIGN_REFERRAL_CODE, orgMember.userId)){
            packageDays = Play.application().configuration().getInt("campaign.agent.packagedays");
        }
        return packageDays;
    }

    /**
     * NOTE: for now this check is only valid for STUDENT addition
     *
     * @param addOrgMemberMappingReq
     * @return
     * @throws VedantuException
     */
    protected List<OrgSection> checkIfAddMappingAllowed(
            AddOrgMemberMappingReq addOrgMemberMappingReq) throws VedantuException {
        LOGGER.error("checkIfAddMappingAllowed Inside checkIfAddMappingAllowed");
        LOGGER.debug("checking for sectionids: " + addOrgMemberMappingReq.sectionIds);
        if(!StringUtils.isEmpty(addOrgMemberMappingReq.userId) && !StringUtils.isEmpty(addOrgMemberMappingReq.targetUserId)){
            if(addOrgMemberMappingReq.userId.equalsIgnoreCase(addOrgMemberMappingReq.targetUserId)){
                OrgMember orgMember = OrgMemberDAO.INSTANCE.getMemberByUserId(
                        addOrgMemberMappingReq.orgId, addOrgMemberMappingReq.userId);
                OrgMemberState orgMemberState = orgMember._getMemberState(System.currentTimeMillis());
                LOGGER.error("checkIfAddMappingAllowed OrgMemberState is "+orgMemberState.name());
                if(orgMemberState == OrgMemberState.BLOCKED){
                    throw new VedantuException(VedantuErrorCode.MEMBER_IS_BLOCKED, "Your Profile Is De-Activated");
                }
            }else{
                OrgMember salesPerson = OrgMemberDAO.INSTANCE.getMemberByUserId(
                        addOrgMemberMappingReq.orgId, addOrgMemberMappingReq.userId);
                OrgMember orgMember = OrgMemberDAO.INSTANCE.getMemberByUserId(
                        addOrgMemberMappingReq.orgId, addOrgMemberMappingReq.targetUserId);
                OrgMemberState salesPersonState = salesPerson._getMemberState(System.currentTimeMillis());
                OrgMemberState orgMemberState = orgMember._getMemberState(System.currentTimeMillis());
                if(orgMemberState == OrgMemberState.BLOCKED){
                    throw new VedantuException(VedantuErrorCode.MEMBER_IS_BLOCKED, "Student Profile Is De-Activated");
                }
                if(salesPersonState == OrgMemberState.BLOCKED){
                    throw new VedantuException(VedantuErrorCode.MEMBER_IS_BLOCKED, "Your Profile Is De-Activated");
                }
            }
        }
        List<OrgSection> orgSections = OrgSectionDAO.INSTANCE.getSectionsByIds(
                addOrgMemberMappingReq.orgId, addOrgMemberMappingReq.programId,
                ObjectIdUtils.toObjectIds(addOrgMemberMappingReq.sectionIds, true));
        if (CollectionUtils.isEmpty(orgSections)) {
            String msg = "Can not find any section for given sectionIds : "
                    + addOrgMemberMappingReq.sectionIds;
            LOGGER.error(msg);
            throw new VedantuException(VedantuErrorCode.ORGANIZATION_PROGRAM_SECTION_NOT_FOUND, msg);
        }

        if (addOrgMemberMappingReq.targetProfile != OrgMemberProfile.STUDENT) {
            return orgSections;
        }
        // now verify the transactionId if the section is open and paid
        // if any section is paid in the list then only one action can be
        // performed (adding to one
        // section)
        int sectionsLength = orgSections.size();
        for (OrgSection orgSection : orgSections) {
            if (AccessScope.OPEN.equals(orgSection.accessScope)
                    && RevenueModel.PAID.equals(orgSection.revenueModel)) {
                if (sectionsLength > 1) {
                    throw new VedantuException(VedantuErrorCode.ACTION_NOT_ALLOWED,
                            "You can add a student to only one paid program at a time.");
                }
                // this section is paid so now verify and mark the transaction
                // consumed
                SrcEntity item = new SrcEntity(EntityType.SECTION, orgSection._getStringId());
                String transactionId = addOrgMemberMappingReq.transactionId;
                if (StringUtils.isEmpty(transactionId)) {
                    Organization org = OrganizationDAO.INSTANCE
                            .getOrganizationById(addOrgMemberMappingReq.orgId);
                    if (StringUtils.isEmpty(addOrgMemberMappingReq.sellerReferenceNo)
                            || StringUtils.isEmpty(addOrgMemberMappingReq.pointOfSale)
                            || !(org.__isValidPointOfSale(addOrgMemberMappingReq.pointOfSale))) {
                        OrgMember orgMember = OrgMemberDAO.INSTANCE.getMemberByUserId(
                                addOrgMemberMappingReq.orgId, addOrgMemberMappingReq.targetUserId);
                        throw new VedantuException(
                                VedantuErrorCode.INVALID_INPUT_DATA,
                                "Data provided is not sufficient. Please check if correct value of TransactionId or Seller Reference No["
                                        + addOrgMemberMappingReq.sellerReferenceNo
                                        + "] with its Point Of Sale["
                                        + addOrgMemberMappingReq.pointOfSale
                                        + "] are provided for user : "
                                        + orgMember.firstName
                                        + " "
                                        + orgMember.lastName
                                        + (StringUtils.isEmpty(orgMember.email) ? "" : ", Email: "
                                                + orgMember.email));
                    }
                    // now we should create an order and transaction for this
                    // record
                    SrcEntity customer = new SrcEntity(EntityType.USER,
                            addOrgMemberMappingReq.targetUserId);
                    addOrgMemberMappingReq.transactionId = createThirdPartyOrderAndTransaction(
                            customer, addOrgMemberMappingReq.userId, DeviceType.WEB,
                            orgSection._getSellableItemDetails(),
                            addOrgMemberMappingReq.pointOfSale,
                            addOrgMemberMappingReq.sellerReferenceNo);
                } else {
                    TransactionDAO.INSTANCE.verifyTransactionInfo(item, transactionId);
                }
            }
        }
        return orgSections;
    }

    private String createThirdPartyOrderAndTransaction(SrcEntity customer, String userId,
            DeviceType deviceType, SellableItemDetails sellableItemInfo, String pointOfSale,
            String sellerReferenceNo) throws VedantuException {

        Order order = OrderManager.createOrder(userId, deviceType, customer);

        OrderItemDetails orderItemDetails = new OrderItemDetails();

        orderItemDetails.period = new Interval(System.currentTimeMillis(), Interval.NO_END);

        OrderManager.addItemToOrder(order, sellableItemInfo,
                ItemCategory.valueOf(sellableItemInfo.item.type.name()), 1, StringUtils.EMPTY,
                orderItemDetails, new Location());

        String transactionId = OrderManager.createThirdPartyTransaction(userId, order, deviceType,
                sellableItemInfo.costRate, pointOfSale, sellerReferenceNo, customer, null, null);
        //
        // VedantuTransactionManager transactionManager =
        // VedantuTransactionManager.getInstance();
        //
        // String transactionId =
        // transactionManager.getVedantuTransactionId(userId, order.orderId,
        // StringUtils.EMPTY, deviceType, costRate.value,
        // costRate.currencyCode);
        //
        // Transaction transaction =
        // TransactionDAO.INSTANCE.getTransaction(transactionId);
        // transaction.amountPaid = costRate.value;
        // transaction.paymentChannel = Transaction.PAYMENT_CHANNEL_THIRD_PATY;
        // transaction.pointOfSale = pointOfSale;
        // transaction.sellerReferenceNo = sellerReferenceNo;
        // transaction.status = TransactionStatus.SUCCESS;
        // transaction.transactionTime =
        // String.valueOf(System.currentTimeMillis());
        // transaction.type = TransactionType.THIRD_PARTY_CREDIT;
        // transaction.ipAddress =
        // Http.Context.current().request().getHeader("X-Real-IP");
        // TransactionDAO.INSTANCE.save(transaction);
        //
        // User user = UserDAO.INSTANCE.getById(customer.id);
        // order.billingEmail = user._getCommunicationEmail();
        // order.ipAddress = transaction.ipAddress;
        // order.orderState = OrderState.CONFIRMED;
        // order.pointOfSale = transaction.pointOfSale;
        // order.sellerReferenceNo = transaction.sellerReferenceNo;
        // transactionManager.updateOrderAndGetPaymentReceivedRes(order,
        // transaction);
        return transactionId;
    }

    protected void verifyExtraInputFields(AddOrgMemberReq addMemberReq) throws VedantuException {

        Map<String, OrgMemberExtraInfo> extraInputFieldsmap = convertToInputFieldMap(addMemberReq.extraInfo);

        List<InputFieldInfo> orgExtraInfos = organization.extraMemberInfoFields == null ? null
                : organization.extraMemberInfoFields.get(addMemberReq.profile);

        if (CollectionUtils.isNotEmpty(orgExtraInfos)) {

            List<String> missingFields = new ArrayList<String>();

            List<String> invalidFields = new ArrayList<String>();
            for (InputFieldInfo inputFieldInfoFromOrg : orgExtraInfos) {
                OrgMemberExtraInfo iFieldInfo = extraInputFieldsmap.get(inputFieldInfoFromOrg.name);

                if (inputFieldInfoFromOrg.required
                        && (iFieldInfo == null || StringUtils.isEmpty(iFieldInfo.value))) {
                    missingFields.add(inputFieldInfoFromOrg.name);
                    continue;
                }
                if (iFieldInfo != null
                        && StringUtils.isNotEmpty(iFieldInfo.value)
                        && !inputFieldInfoFromOrg.validationType.validate(inputFieldInfoFromOrg,
                                iFieldInfo.value)) {

                    invalidFields.add(inputFieldInfoFromOrg.name + " : " + iFieldInfo.value);
                }
            }

            if (CollectionUtils.isNotEmpty(missingFields)) {
                throw new VedantuException(VedantuErrorCode.MISSING_PARAMETERS,
                        "missing required fields : " + StringUtils.join(missingFields, ","));
            }

            if (CollectionUtils.isNotEmpty(invalidFields)) {
                throw new VedantuException(VedantuErrorCode.MISSING_PARAMETERS,
                        " invalid fields value " + StringUtils.join(invalidFields, ","));
            }
        }
        extraInputFieldsmap.clear();

    }

    protected Map<String, OrgMemberExtraInfo> convertToInputFieldMap(
            List<OrgMemberExtraInfo> inputFieldInfos) {

        Map<String, OrgMemberExtraInfo> fieldsMap = new HashMap<String, OrgMemberExtraInfo>();
        if (CollectionUtils.isEmpty(inputFieldInfos)) {
            return fieldsMap;
        }
        for (OrgMemberExtraInfo inputFieldInfo : inputFieldInfos) {
            fieldsMap.put(inputFieldInfo.name, inputFieldInfo);
        }
        return fieldsMap;
    }

    protected static AddOrgMemberMappingRes addOrgMemberMapping(
            AddOrgMemberMappingReq addOrgMemberMappingReq, boolean noExceptionOnExistingMapping)
            throws VedantuException {

        Set<String> tSectionIds = null == addOrgMemberMappingReq.sectionIds ? null
                : new HashSet<String>(addOrgMemberMappingReq.sectionIds);
        Set<String> tCourseIds = null == addOrgMemberMappingReq.courseIds ? null
                : new HashSet<String>(addOrgMemberMappingReq.courseIds);
        MutableBoolean isAdded = new MutableBoolean(false);
        OrgMember orgMember = OrgMemberDAO.INSTANCE.addOrgMemberMapping(
                addOrgMemberMappingReq.orgId, addOrgMemberMappingReq.targetUserId,
                addOrgMemberMappingReq.targetOrgMemberId, addOrgMemberMappingReq.programId,
                addOrgMemberMappingReq.centerId, tSectionIds, tCourseIds, isAdded,
                noExceptionOnExistingMapping, addOrgMemberMappingReq.transactionId,
                addOrgMemberMappingReq.packageDays);
        String orderId = getOrderIdForAddedSection(orgMember,
                addOrgMemberMappingReq.sectionIds.get(0));

        if (addOrgMemberMappingReq.saleDetailsInfo != null) {
            SaleDetails saleDetails = SaleDetailsDAO.INSTANCE.addSaleDetails(
                    addOrgMemberMappingReq.saleDetailsInfo, orderId,
                    addOrgMemberMappingReq.pointOfSale, addOrgMemberMappingReq.userId,
                    addOrgMemberMappingReq.targetOrgMemberId, addOrgMemberMappingReq.orgId,
                    addOrgMemberMappingReq.sectionIds.get(0));
            OrgMemberDAO.INSTANCE.addSaleDetailsToMapping(addOrgMemberMappingReq.orgId,
                    addOrgMemberMappingReq.targetUserId, addOrgMemberMappingReq.sectionIds.get(0),
                    saleDetails._getStringId());
        }
        // TODO: add relationship between saleDetails and orgMember mapping
        AddOrgMemberMappingRes addOrgMemberMappingRes = new AddOrgMemberMappingRes(
                orgMember._getStringId(), orgMember.recordState, isAdded.booleanValue());
        return addOrgMemberMappingRes;
    }

    private static String getOrderIdForAddedSection(OrgMember orgMember, String sectionId) {
        String orderId = "0";
        for (OrgMemberMappingInfo mapping : orgMember.mappings) {
            if (mapping.sectionId.equals(sectionId)) {
                orderId = mapping.orderId;
            }
        }
        return orderId;
    }

    public static String getAutogeneratedMemeberIdKeyPrefix() {

        return Play.application().configuration()
                .getString("org.default.memberid.prefix", StringUtils.EMPTY);
    }

    public abstract UserAuthRes authenticate(String username, String password)
            throws VedantuException;

    public abstract AddOrgMemberRes addMember(AddOrgMemberReq req, boolean isMemberIdSysGenerated)
            throws VedantuException;

    public abstract AddOrgMemberMappingRes addMemberMapping(
            AddOrgMemberMappingReq addOrgMemberMappingReq, boolean noExceptionOnExistingMapping)
            throws VedantuException;

    public abstract String getMemberUsername(String orgId, String memberId) throws VedantuException;

    public abstract boolean isUpdateValid(Set<String> updateList) throws VedantuException;

}
