include "commons.dev.conf"

http.port=19019
jvm.memory="-Xms64M -Xmx128M"


application.session.cookie="VEDANTU_DEV_SESSION"
play {
  akka {
    event-handlers = ["akka.event.slf4j.Slf4jEventHandler"]
    loglevel = WARNING
    actor {
      default-dispatcher = {
        fork-join-executor {
          parallelism-factor = 10
          parallelism-max = 100
        }
      }
    }
  }
}
