include "commons.prod.conf"

http.port=19019
jvm.memory="-Xms512M -Xmx2048M"

mime.types.file.path="conf/MimeTypes"

play {
  akka {
    event-handlers = ["akka.event.slf4j.Slf4jEventHandler"]
    loglevel = WARNING
    actor {
      default-dispatcher = {
        fork-join-executor {
          parallelism-factor = 10
          parallelism-max = 100
        }
      }
    }
  }
}


