include "commons.qa.conf"

http.port=19019
jvm.memory="-Xms64M -Xmx512M"


play {
  akka {
    event-handlers = ["akka.event.slf4j.Slf4jEventHandler"]
    loglevel = WARNING
    actor {
      default-dispatcher = {
        fork-join-executor {
          parallelism-factor = 10
          parallelism-max = 100
        }
      }
    }
  }
}


