#spring.data.mongodb.host=localhost
spring.data.mongodb.host=3.7.93.20
spring.data.mongodb.port=27017
spring.data.mongodb.database=prodlp
server.port=8010
amazon.s3.bucket.allowedorigins=["http://*.learnpedia.in","https://*.learnpedia.in"]
amazon.s3.accessKey="__REDACTED__"
amazon.s3.secretKey="__REDACTED__"
amazon.s3.bucket.identifier=uprep
application.mode=""
img.host=""
fwkId=qa
fs.class=S3Handler
media.types.file.path=../../commons/conf/MediaTypes
learnpedia.id=5551bf80e4b053fbc7baf90d
application.session.cookie="VEDANTU_LOCAL_SESSION"
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
#default wait time before produce a event to consume
reproduce.wait.time=300
#producer maxt tries 
max.tries=3
#challenge configurations
challenge.leaderboard.min.attempt=1
#task batchSize for event threadManager
task.batch.size="EXPORT:10;CALCULATE_SIZE:10"
#task number of threads for event threadManager
task.thread.number="EXPORT:3;CALCULATE_SIZE:10"
#sleep time for thread for task threadManager
task.sleep.time="EXPORT:10000"
smtp.host="email-smtp.us-east-1.amazonaws.com"
smtp.port=25
#smtp.ssl=
smtp.tls=yes
smtp.user="__AWS_ACCESS_KEY_REDACTED__"
smtp.password="__REDACTED__"
email.configuration.enabled=yes
