# Local mongodb configuration.
#.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=lmsdb
#spring.data.mongodb.repositories.enabled=true
#spring.data.mongodb.uri=spring.data.mongodb.uri=mongodb://127.0.0.1:27017/lm    sdb

# App config
#spring.application.name=UserApplication

spring.data.mongodb.host=3.7.135.193

spring.data.mongodb.port=27017
spring.data.mongodb.database=prodlp
server.port=8050

