#spring.data.mongodb.host=localhost
spring.data.mongodb.host=3.7.93.20
spring.data.mongodb.port=27017
spring.data.mongodb.database=prodlp
server.port=8060
amazon.s3.bucket.identifier=uprep
img.host="https://imgqa.learnpedia.in"
fs.class=S3Handler
application.session.cookie="VEDANTU_LOCAL_SESSION"
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

