log4j.rootLogger=DEBUG, file

log4j.logger.net.sf.ehcache=ERROR, file
log4j.logger.org.apache.hadoop=ERROR, file
log4j.logger.org.elasticsearch=ERROR, file
log4j.logger.net.spy.memcached=ERROR, file
log4j.logger.netty.channel=ERROR, file
log4j.logger.org.apache.commons=ERROR, file
log4j.logger.org.restlet=INFO, file
log4j.logger.play=INFO
log4j.logger.com.ning.http=ERROR, file
log4j.logger.com.amazonaws=ERROR, file
log4j.logger.org.apache.http.wire=ERROR, file

log4j.appender.file=uk.org.simonsite.log4j.appender.TimeAndSizeRollingAppender
log4j.appender.file.File=logs/tools.log
log4j.appender.file.DateRollEnforced=true
log4j.appender.file.DatePattern=.yyyy-MM-dd
log4j.appender.file.MaxFileSize=200MB
log4j.appender.file.maxRollFileCount=3
log4j.appender.file.compressionAlgorithm=GZ
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=[%d %-5p] - %m%n