package com.lms.common.exception;

public enum VedantuErrorCode {

    // ~~~~ services internal error ~~~~~
    INSUFFICIENT_BOARDS_IN_TARGET,
    CAN_NOT_EXECUTE,
    SERVICE_ERROR,
    MISSING_PARAMETERS,
    SHOULD_NOT_BE_NULL,
    INVALID_ID,
    MISSING_FILE,
    UNSUPPORTED_FILE_TYPE,
    FILE_UPLOAD_ERROR,
    NO_STORAGE_FOUND,
    NO_DAO_FOUND,
    NO_CONTENT_FOUND,
    CONTENT_ASSOCIATED_WITH_QUESTION,
    CONTENT_IS_ALREADY_DELETED,
    CONTENT_IS_PUBLISHED,
    CONTENT_HAD_BEEN_PUBLISHED_BEFORE,
    REINDEXING_FAILED,
    CAN_NOT_GENERATE_SECURITY_CREDENTIALS,
    ALREADY_LOGGED_IN,
    ALREADY_LOGGED_OUT,
    USER_LOGIN_NOT_FOUND,
    USER_ALREADY_ACTIVE,
    USER_ALREADY_DEACTIVATED_WITH_NO_FUTURE_ACTIVATION,
    STORAGE_EXCEPTION,
    FAILED_TO_EXPORT,
    NO_EXPORT_RECORD_FOUND,
    EXPORT_ABORTED,
    CAN_NOT_BE_UPDATED,
    ALREADY_DELETED,
    UNDER_PROCESSING,
    TAGS_NOT_SPECIFIED,
    // Add Error-Codes module wise if needed

    MODULE_LIST_EMPTY,
    MODULE_DOES_NOT_EXISTS,
    MODULE_IN_DRAFT_STATE,
    CONTENT_LIST_EMPTY,
    INVALID_POSITION,

    MODULE_NOT_FOUND,

    // ~~~ USER SERVICE ~~~
    USER_ALREADY_EXISTS,
    AUTHENTICATION_FAILED,
    USER_NOT_FOUND,
    USER_NO_VERIFIED_EMAIL,
    INVALID_DATE_FORMAT,
    INVALID_CONTACT_NUMBER,
    INVALID_VERIFICATION_CODE,
    INCORRECT_UPDATE_DATA_PROVIDED,
    EMAIL_UNSUBSCRIPTION_FAILED,
    EMAIL_SUBSCRIPTION_FAILED,
    ALREADY_UNSUBSCRIBED,

    // ~~~ ORGANIZATION SERVICE ~~~
    ORGANIZATION_ALREADY_EXISTS,
    ORGANIZATION_NOT_FOUND,
    ORGANIZATION_ALREADY_APPROVED,
    ORGANIZATION_MEMBER_NOT_FOUND,
    ORGANIZATION_MEMBER_ALREADY_EXISTS,
    ORGANIZATION_MEMBER_MAPPING_NOT_FOUND,
    ORGANIZATION_MEMBER_MAPPING_ALREADY_EXISTS,
    ORGANIZATION_CENTER_NOT_FOUND,
    ORGANIZATION_MEMBER_ID_PATTERN_NOT_ALLOWED,
    ORGANIZATION_MISSING_MEMBER_ID_AND_EMAIL,
    ORGANIZATION_CENTER_ALREADY_EXISTS,
    ORGANIZATION_DEPARTMENT_NOT_FOUND,
    ORGANIZATION_DEPARTMENT_ALREADY_EXISTS,
    ORGANIZATION_PROGRAM_NOT_FOUND,
    ORGANIZATION_PROGRAM_ALREADY_EXISTS,
    ORGANIZATION_PROGRAM_CENTER_NOT_FOUND,
    ORGANIZATION_PROGRAM_CENTER_ALREADY_EXISTS,
    ORGANIZATION_PROGRAM_SECTION_NOT_FOUND,
    SECTION_LIST_NOT_SPECIFIED,
    ORGANIZATION_PROGRAM_SECTION_ALREADY_EXISTS,
    ORGANIZATION_USER_ASSOCIATION_NOT_FOUND,
    STUDENT_FILE_UNPARSEABLE,
    UNABLE_TO_CREATE_ORGANIZATION,
    EXTERNAL_AUTH_SUPPORTED,
    INVALID_WEBSITE,
    INVALID_PACKAGES_PRICING,
    TNC_NOT_ACCEPTED,
    MEMBER_IS_BLOCKED,
    DUPLICATE_CONTACTS_EXIST,
    SMS_GATEWAY_DETAILS_NOT_FOUND,

    // ~~~~~~~~ External Auth ~~~~~~~~~~~~
    ORG_END_POINT_NOT_REACHABLE,
    ORG_SIGNUP_NOT_SUPPORTED,
    ORG_ENROLLMENT_NOT_SUPPORTED,

    // ~~~~~~~~~~ Licensing ~~~~~~~~~~
    LICENSING_PLAN_ALREADY_EXISTS,
    LICENSING_PLAN_ALREADY_ACTIVE,
    INVALID_LICENSING_PLAN,
    LICENSE_INVALIDATED,
    LICENSING_PLAN_IS_BEING_USED,
    INVALID_LICENSING_STATE,

    // ~~~ CONTENT SERVICE ~~~
    // question content and answer related errors
    INVALID_ANSWER_FORMAT,
    INVALID_QUESTION_FORMAT,
    QUESTION_NOT_FOUND,
    ACCESS_DENIED,
    QUESTION_CANNOT_BE_EDITED,
    QUESTION_SUBJECT_CANNOT_BE_EDITED,
    // ~~~ STATUS FEED SERVICE ~~~
    FORMAT_NOT_ALLOWED,
    INVALID_STATUS_FEED,
    UPLOAD_ERROR,
    FILE_NOT_FOUND,
    INVALID_URL,
    INVALID_DATE_TIME,
    INVALID_UNSECURED_URL,
    DATE_TIME_LESS_THAN_CURRENT,
    FROM_DATE_TIME_LESS_THAN_CURRENT,
    TILL_DATE_TIME_LESS_THAN_CURRENT,
    // ~~~ BOARD SERVICE ~~~
    // boards related constants
    BOARD_NOT_FOUND,
    BOARD_FILE_UNPARSEABLE,

    // ~~~ EVENT-BUS-MGNT SERVICE ~~~
    NO_TASK_RUNNING,
    INVALID_EVENT_TYPE,
    EVENT_NOT_SCHEDULED,

    // ~~~ CMDS SERVICE ~~~
    PARENT_DIRECTORY_NOT_FOUND,
    FOLDER_NOT_FOUND,
    FOLDER_ALREADY_EXISTS,
    CAN_NOT_BE_REMOVED,
    INCORRECT_ORGANIZATION_ENTITY,
    ALREADY_ADDED,
    FOLDER_CAN_NOT_BE_MOVED,
    ROOT_FOLDER_CAN_NOT_BE_MOVED,
    FOLDER_CAN_NOT_BE_MOVED_TO_CHILD_FOLDER,
    FOLDER_CAN_NOT_BE_CHILD_OF_SELF,
    CONTENT_CAN_NOT_BE_MOVED,
    CONTENT_NOT_FOUND,
    CONTENT_IN_TEMPORARY_STAGE,
    NOT_PUBLISHED,
    INVALID_SECTION_ID,
    ALREADY_PUBLISHED,
    NO_BOARD_TREE_SPECIFIED,
    INVALID_COST_RATE,
    INVALID_CURRENCY_CODE,

    CATEGORY_ALREADY_EXISTS,
    CATEGORY_DOES_NOT_EXISTS,
    CATEGORY_LIST_NOT_DEFINED,

    QUESTION_OPTIONS_ARE_MISSING,
    CMDS_QUESTION_NOT_FOUND,
    QUESTION_SET_CAN_NOT_BE_SAVED,
    QUESTION_SET_SIZE_NOT_MATCHED,
    OPTION_DUPLICATION_OCCURED,

    UNKNOWN_QUESTION_TYPE,
    NEW_SOLUTION_IS_MISSING,
    SOLUTION_EMPTY,
    INCORRECT_HINT_FORMAT,
    INVALID_QUESTION_TYPE,
    CAN_NOT_PUBLISH_QUESTION,
    DIFFICULTY_NOT_SPECIFIED,
    ILLEGAL_QUESTION_OPTION_SPECIFIED,
    INVALID_FOLDER_ID,
    INVALID_CENTER_ID,
    QUESTION_SET_NOT_FOUND,
    INVALID_START_SPECIFIED,
    CAN_NOT_BE_PUBLISHED,
    NO_SOLUTIONINFO_PROVIDED,
    INVALID_TYPE,

    INVALID_JOB_ID,
    UNSUPPORTED_CONTENT_TYPE,
    UNSUPPORTED_ORG_TYPE,
    EMAIL_CAN_NOT_BE_SEND,
    NOT_VALID_CMDS_CONTENT,

    DOCUMENT_NOT_FOUND,
    /** Encryption errors */
    ENCRYPTION_FAILED,
    /** valid data */
    NO_VIDEO_ID_PROVIDED,
    VIDEO_INFO_NOT_EXTRACTED,
    VIDEO_NOT_FOUND,
    DURATION_NOT_FOUND,
    NOT_CONVERTED,
    VIDEO_FORMAT_NOT_SUPPORTED,
    CONVERSION_FAILED,
    CONTENT_NOT_VISIBLE,
    // questions
    OPTIONS_NOT_SPECIFIED,
    // cmds parsing specific errors
    SUBJECT_NOT_FOUND,
    TOPIC_NOT_FOUND,
    SUBTOPIC_NOT_FOUND,
    FROM_DATE_GREATER_THAN_TILL_DATE,

    // ~~~ DISCUSSION SERVICE ~~~CAN_NOT_SECURITY_CREDENTIALS,
    DISCUSSION_NOT_FOUND,
    COMMENT_NOT_FOUND,
    COMMENTING_NOT_ALLOWED,
    QUESTION_OPTION_UNSPECIFIED,

    // ~~~ COMMUNICATION SERVICE ~~~
    // ~~~ Messages ~~~
    INVALID_USER_ID,
    INVALID_MESSAGE_ID,
    INVALID_CONVERSATION_ID,
    CAN_NOT_BE_DELIVERED,
    INVALID_ENTITY_TYPE,
    INVALID_ENTITY_ID,
    NOT_ALLOWED,
    // ~~~ Notices ~~~
    // ~~~ Chat ~~~
    // ~~~ Remarks ~~~
    VIEWING_NOT_ALLOWED,
    POSTING_NOT_ALLOWED,

    // ~~~ NEWS FEED SERVICE ~~~
    INVALID_SIZE,
    ACTIVITY_NOT_AVAILABLE,
    // ~~~ SOCIAL SERVICE ~~~
    ALREADY_COMPLETED,
    ALREADY_VOTED,
    ALREADY_FOLLOWING,
    NOT_FOLLOWING,
    ACTION_NOT_ALLOWED,
    CAN_NOT_SHARE_WITH_SELF,
    SHARING_NOT_ALLOWED,

    // ~~~ CHALLENGE SERVICE ~~~
    MISSING_POINT_DEDUCTION_VALUE,
    INVALID_POINT_DEDUCTION_VALUE,
    CHALLENGE_NOT_FOUND,
    INVALID_LIFE_TIME,
    PRIVATE_CHALLENGE,
    CHALLENGE_ENDED,
    ALREADY_ATTEMPTED,
    ENTITY_NOT_FOUND,
    INVALID_TOKEN,
    NO_HINT,

    // ~~~ CHANNEL SERVICE ~~~
    CHANNEL_NOT_FOUND,
    CHANNEL_ALREADY_EXIST,
    ALREADY_SHARED,

    // ~~ offline test result upload
    INVALID_INPUT_DATA,
    TEST_NOT_FOUND,
    TEST_ALREAY_PRESENT,
    TEST_ENDED,
    TEST_PAUSED,
    TEST_PAUSED_RESUME_AGAIN,
    ASSIGNMENT_NOT_FOUND,
    ASSIGNMENT_ALREAY_PRESENT,
    INCOMPLETE_TEST,
    INCOMPLETE_ASSIGNMENT,
    INVALID_METADATA,
    METADATA_NOT_FOUND,
    QUESTION_MAX_COUNT_EXCEED,
    UNABLE_TO_CREATE_TEST,

    // ~~~ ANALYTICS SERVICE ~~~
    UNATTEMPTABLE_ENTITY,
    MULTI_ATTEMPTS_NOT_ALLOWED,
    ATTEMPT_NOT_FOUND,
    NOT_ATTEMPTED,
    ATTEMPT_IN_PROGRESS,
    INVALID_QUESTION_ID,
    ANALYTICS_NOT_FOUND,

    // ~~~~PUBLISHING STATE ~~~~~~
    INCOMPLETE_PUBLISHABLE_STATE,

    // ~~~~~~~~~~ Billing service ~~~~~
    INVALID_ITEM,
    INVALID_ORDER,
    INVALID_ORDER_ID,
    ORDER_STATE_NOT_ALLOWED,
    INVALID_TRANSACTION,
    INCOMPLETE_TRANSACTION,
    TRANSACTION_FAILED,
    TRANSACTION_ALREADY_COMPLETED,
    UNKNOWN_PAYMENT_CHANNEL,

 // ~~~ ACCESS CODES ERROR CODE ~~~
    INVALID_CODE,
    ITEM_ALREADY_VERIFIED_WITH_DIFFERENT_DEVICE,
    ITEM_ALREADY_VERIFIED_FOR_DIFFERENT_USER,
    ACCESS_CODE_DOES_NOT_EXISTS,
    ACCESS_CODE_NOT_VERIFIED,
    ITEMS_HAVE_DIFFERENT_CURRENCY_CODE,
    COST_RATE_NOT_DEFINED_FOR_ITEM,
    // ~~~ SLUG RELATED ERROR CODE ~~~
    INVALID_SLUG,
    INVALID_REFERER,
    INVALID_ACCESS_CODE,
    SLUG_NOT_AVAILABLE,
    REFERRER_NOT_AVAILABLE,
    CAN_NOT_CONVERT_TO_PDF,
    UNKNOWN_APP_TYPE,
    INVALID_STATUS,
    // ~~~~~~~~ SD CARD ERRORES ~~~~~~~~~~~~
    NOT_ENOUGH_SPACE,

    // ~~~ COUPON CODES ERROR CODE ~~~
    COUPON_ALREADY_EXISTS,
    COUPON_CODE_EXPIRED,
    COUPON_NOT_APPLICABLE,
    COUPON_CODE_NOT_FOUND,
    ERROR_APPLY_COUPON,
    INVALID_COUPON_CODE,

  //~~~ Campaign ERROR CODE ~~~
    DOES_NOT_EXIST,
    ANOTHER_ACTIVE_CAMPAIGN_EXIST,
    // ~~~~ SALE DETAILS ERRORS ~~~~~~
    SALE_DETAILS_NOT_FOUND,
    SALE_DETAILS_MISMATCH,
    //For Category
    INVALID_CATEGORY_ID, CAN_NOT_EMBED, BOARD_MAPPING_NOT_FOUND, ORGANISATION_MAPPING_NOT_FOUND,INCOMPLETE_BOARD_MAPPING,
    //~~~Download TestUser Data ERROR CODE ~~~
    CANNOT_WRITE_FILE, ANALYTICS_GENERATION_UNDER_PROCESS, TEST_IS_NOT_LIVE, PRIVATE_PROGRAM, CAN_NOT_SHARE_THIS_PROGRAM, NO_SUBJECT_FOUND, PUBLISH_IN_PROGRESS,

    EMAIL_SHOULD_MANDATORY
}