"use client";

import { useState } from "react";

export type RelatedItem = {
  id: string;
  type: "VIDEO" | "BOOK" | "DOCUMENT";
  name: string;
  url: string | null;
  embedUrl: string | null;
  provider: string | null;
};

function youtubeThumb(embedUrl: string | null): string | null {
  const m = embedUrl?.match(/embed\/([A-Za-z0-9_-]{6,})/);
  return m ? `https://img.youtube.com/vi/${m[1]}/hqdefault.jpg` : null;
}

const TYPE_ICON: Record<RelatedItem["type"], string> = { VIDEO: "▶️", BOOK: "📖", DOCUMENT: "📄" };

// A single, explicit "Aira recommends" video callout — shown for Guided
// answers when a real video already exists in the library for this doubt's
// tagged chapter. Deliberately NOT generated by the AI model: the model
// never sees or invents a URL here, this is the exact same grounded
// relatedContentFor() lookup the generic strip below uses, just presented as
// a direct recommendation instead of a browsable row. Keeps the "no
// hallucinations" rule intact — a real video or nothing, never a guessed one.
export function AiraRecommendedVideo({ item, onPlay, playing }: { item: RelatedItem; onPlay: () => void; playing: boolean }) {
  const thumb = youtubeThumb(item.embedUrl);
  return (
    <div className="mt-3 rounded-xl border border-blue-100 bg-blue-50/60 p-3">
      <div className="text-xs font-semibold text-blue-700">🎥 Aira recommends watching this</div>
      <button onClick={onPlay} className="mt-2 flex w-full items-center gap-3 text-left">
        <div className="relative h-14 w-24 shrink-0 overflow-hidden rounded-lg bg-gradient-to-br from-sky-400 via-blue-500 to-indigo-600">
          {thumb ? (
            // eslint-disable-next-line @next/next/no-img-element
            <img src={thumb} alt="" className="absolute inset-0 h-full w-full object-cover" />
          ) : (
            <span className="absolute inset-0 flex items-center justify-center text-xl opacity-80">▶️</span>
          )}
          <span className="absolute left-1/2 top-1/2 flex h-6 w-6 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full bg-black/50 text-xs text-white">
            ▶
          </span>
        </div>
        <span className="text-sm font-medium text-[#16233D]">{item.name}</span>
      </button>
      {playing && (
        <div className="mt-3 overflow-hidden rounded-xl bg-black shadow-sm">
          {item.embedUrl ? (
            <div className="aspect-video w-full max-w-md">
              <iframe
                src={item.embedUrl}
                className="h-full w-full"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
                title={item.name}
              />
            </div>
          ) : item.url ? (
            <video src={item.url} controls className="mt-2 w-full max-w-md" />
          ) : null}
        </div>
      )}
    </div>
  );
}

// "Matching solutions" strip shown under Aira's answer — content already on
// the platform tagged to the same chapter as the doubt, same idea as
// browsing the Digital Library but surfaced right where the question was
// asked. Videos play inline on click; books/documents open in a new tab.
export default function RelatedContent({ items }: { items: RelatedItem[] }) {
  const [playingId, setPlayingId] = useState<string | null>(null);
  if (!items.length) return null;
  const playing = items.find((i) => i.id === playingId);

  return (
    <div className="mt-3">
      <div className="text-xs font-medium text-[#8890A1]">Here's related material from the library</div>
      <div className="mt-2 flex gap-3 overflow-x-auto pb-1">
        {items.map((item) => {
          const thumb = item.type === "VIDEO" ? youtubeThumb(item.embedUrl) : null;
          const isVideo = item.type === "VIDEO";
          const card = (
            <div className="relative flex h-24 w-40 shrink-0 flex-col justify-end overflow-hidden rounded-xl bg-gradient-to-br from-sky-400 via-blue-500 to-indigo-600 shadow-sm transition hover:shadow-md">
              {thumb ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img src={thumb} alt="" className="absolute inset-0 h-full w-full object-cover" />
              ) : (
                <span className="absolute inset-0 flex items-center justify-center text-3xl opacity-80">
                  {TYPE_ICON[item.type]}
                </span>
              )}
              <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-black/0 to-black/0" />
              {isVideo && (
                <span className="absolute left-1/2 top-1/2 flex h-9 w-9 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full bg-black/50 text-white backdrop-blur-sm">
                  ▶
                </span>
              )}
              <div className="relative truncate px-2 pb-1.5 text-[11px] font-medium text-white">{item.name}</div>
            </div>
          );
          return isVideo ? (
            <button key={item.id} onClick={() => setPlayingId(item.id)} className="text-left">
              {card}
            </button>
          ) : item.url ? (
            <a key={item.id} href={item.url} target="_blank" rel="noreferrer">
              {card}
            </a>
          ) : (
            <div key={item.id}>{card}</div>
          );
        })}
      </div>

      {playing && (
        <div className="mt-3 overflow-hidden rounded-xl bg-black shadow-sm">
          {playing.embedUrl ? (
            <div className="aspect-video w-full max-w-md">
              <iframe
                src={playing.embedUrl}
                className="h-full w-full"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
                title={playing.name}
              />
            </div>
          ) : playing.url ? (
            <video src={playing.url} controls className="w-full max-w-md" />
          ) : null}
        </div>
      )}
    </div>
  );
}
