include "commons.dev.conf"

http.port=19015
jvm.memory="-Xms64M -Xmx256M"

#default wait time before produce a event to consume
reproduce.wait.time=300

#producer maxt tries 
max.tries=3

#challenge configurations
challenge.leaderboard.min.attempt=1

#Vedantu website
infographic.link = "https://infodev.vedantu.com"