include "commons.local.conf"

http.port=19012
jvm.memory="-Xms64M -Xmx128M"

#REFERRAL CAMPAIGN CONFIG
#~~~~~~~~~~~~~~~~~~~~~~~~
campaign.referral=""
campaign.section.id=""
campaign.center.id=""
campaign.program.id=""
campaign.agent.packagedays="30"
campaign.user.packagedays="14"

#SMS COUNTRY CONFIG
#~~~~~~~~~~~~~~~~~~~~~~~
smscountry.url="http://api.smscountry.com/SMSCwebservice_bulk.aspx"
smscountry.user="learnpedia"
smscountry.passwd="__REDACTED__"
smscountry.sid="LPEDIA"
smscountry.mtype="N"
smscountry.dr="Y"
otp.size=4

#Learnpedia Organisation Id
#~~~~~~~~~~~~~~~~~~~~~~~~
learnpedia.id="5874a52bc92ed65e3defc7e5"

#Programs Bucket Name
#~~~~~~~~~~~~~~~~~~~~~~
bucket.name="program-qa-learnpediaqa"

#Auto Add Demo Programs
#~~~~~~~~~~~~~~~~~~~~~~~
jeedemo.section.id="58e1e84ba444bd84e57a413a"
jeedemo.center.id="5874a6bbc92ed65e3defc7f9"
jeedemo.program.id="58e1e7efa444bd84e57a412f"

neetdemo.section.id="58db4a48c92ee3ccaf057953"
neetdemo.center.id="5874a6bbc92ed65e3defc7f9"
neetdemo.program.id="58db4a0ac92ee3ccaf057950"

#Leadsquared Campaign Programs
#~~~~~~~~~~~~~~~~~~~~~~~
emp.section.id="59550c82e4b066936712ea5e"
emp.center.id="56936df744aed64166ee09db"
emp.program.id="570f38e144ae7d512b34447d"

jeesoln.section.id="59550ca9e4b066936712ea61"
jeesoln.center.id="56936df744aed64166ee09db"
jeesoln.program.id="570f38e144ae7d512b34447d"

neetseries.section.id="59550cbae4b066936712ea64"
neetseries.center.id="56936df744aed64166ee09db"
neetseries.program.id="570f38e144ae7d512b34447d"

#Programs custom description
#~~~~~~~~~~~~~~~~~~~~~~~

"58e1e84ba444bd84e57a413a.desc"="SCORE (Simple and Complete Online Resource) is a digital learning platform for various competitive exams"
"58e1e84ba444bd84e57a413a.firstPoint"="Videos - 4000+"
"58e1e84ba444bd84e57a413a.secondPoint"="Practice Content - 20000+"
"58e1e84ba444bd84e57a413a.thirdPoint"="Practice Mock Tests - 1800+"
"58e1e84ba444bd84e57a413a.fourthPoint"="Doubts Forum"
"58e1e84ba444bd84e57a413a.imageUrl"="/public/images/programImages/scorejee_online.jpg"

"58db4a48c92ee3ccaf057953.desc"="SCORE (Simple and Complete Online Resource) is a digital learning platform for various competitive exams"
"58db4a48c92ee3ccaf057953.firstPoint"="Videos - 4000+"
"58db4a48c92ee3ccaf057953.secondPoint"="Practice Content - 20000+"
"58db4a48c92ee3ccaf057953.thirdPoint"="Practice Mock Tests - 1800+"
"58db4a48c92ee3ccaf057953.fourthPoint"="Doubts Forum"
"58db4a48c92ee3ccaf057953.imageUrl"="/public/images/programImages/scoreneet_online.jpg"

"5874a700c92ed65e3defc7fd.desc"="SCORE (Simple and Complete Online Resource) is a digital learning platform for various competitive exams"
"5874a700c92ed65e3defc7fd.firstPoint"="Videos - 4000+"
"5874a700c92ed65e3defc7fd.secondPoint"="Practice Content - 20000+"
"5874a700c92ed65e3defc7fd.thirdPoint"="Practice Mock Tests - 1800+"
"5874a700c92ed65e3defc7fd.fourthPoint"="Doubts Forum"
"5874a700c92ed65e3defc7fd.imageUrl"="/public/images/programImages/scorejee_sdcard.jpg"

"5874a749c92ed65e3defc801.desc"="SCORE (Simple and Complete Online Resource) is a digital learning platform for various competitive exams"
"5874a749c92ed65e3defc801.firstPoint"="Videos - 4000+"
"5874a749c92ed65e3defc801.secondPoint"="Practice Content - 20000+"
"5874a749c92ed65e3defc801.thirdPoint"="Practice Mock Tests - 1800+"
"5874a749c92ed65e3defc801.fourthPoint"="Doubts Forum"
"5874a749c92ed65e3defc801.imageUrl"="/public/images/programImages/scoreneet_sdcard.jpg"


#InstaMojo key credentails
#~~~~~~~~~~~~~~~~~~~~~~~
instamojo.env = "test"
instamojo.url = "https://test.instamojo.com/oauth2/token/"
instamojo.clientid = "test_jow34m9BKuNnhHcS2wJQ87W16cZBnRUf5hc"
instamojo.clientsecretkey = "__REDACTED__"