#spring.data.mongodb.host=localhost
spring.data.mongodb.host=3.7.93.20
spring.data.mongodb.port=27017
spring.data.mongodb.database=prodlp
server.port=8070
spring.servlet.multipart.max-file-size=256MB
spring.servlet.multipart.max-request-size=256MB
spring.servlet.multipart.enabled=true
img.host="https://imgqa.learnpedia.in"
application.mode="hello"
fwkId=qa
amazon.s3.bucket.identifier=uprep
amazon.s3.accessKey="__REDACTED__"
image.medium.width=600
image.medium.height=600
image.small.width=200
image.small.height=200
image.large.width=400
image.large.height=400
image.xsmall.width=100
image.xsmall.height=100
fs.class=S3Handler
#fs.class="com.vedantu.commons.fs.handlers.ObjectStorageHandler"
util.temp_dir=/home/ubuntu/learnpedia/temp
fs.local.basedir=/home/ubuntu/learnpedia/temp/fs
