package com.lms.organization.auth;

import com.lms.common.exception.VedantuErrorCode;
import com.lms.common.exception.VedantuException;
import com.lms.common.vedantu.enums.AuthType;
import com.lms.enums.OrgMemberState;
import com.lms.models.AddOrgMemberMappingReq;
import com.lms.models.OrgMember;
import com.lms.models.Organization;
import com.lms.pojo.request.AuthRequest;
import com.lms.pojo.responce.AddOrgMemberMappingRes;
import com.lms.repository.OrgMemberRepo;
import com.lms.user.vedantu.user.pojo.responce.UserAuthRes;
import com.lms.user.vedantu.user.requests.UserAuthReq;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;

import java.util.Date;
import java.util.regex.Pattern;

public abstract class AuthHandler {
    @Autowired
    private OrgMemberRepo orgMemberRepo;
    protected Organization organization;
    public final AuthType authType;
    @Value("${campaign.referral}")
    public String  campaignReferal;
    private static final int     SYSTEM_GENERATED_PASS_LENGTH   = 6;
    private  final Pattern REGEX_SYSGEN_MEMBER_ID_PATTERN = Pattern
            .compile("^"
                    + getAutogeneratedMemeberIdKeyPrefix()
                    + "[0-9]*");
    private static final Logger logger                         = LoggerFactory.getLogger(AuthHandler.class);
    private static final int     DEFAULT_CAMPAIGN_PACKAGE_DAYS  = 365;

    private  final String  CAMPAIGN_REFERRAL_CODE              = campaignReferal;
    @Value("${org.default.memberid.prefix}")
    public String  prefex;

    public AuthHandler(Organization org, AuthType authType) {

        this.organization = org;
        this.authType = authType;

    }
    public  String getAutogeneratedMemeberIdKeyPrefix() {
    return prefex;
    }

    protected OrgMember checkOrgMember(OrgMember orgMember) throws VedantuException {

      //  OrgMember orgMember = orgMemberRepo.findByOrgIdAndMemberId(orgId,memberId);

        if (null == orgMember)
            throw new VedantuException(VedantuErrorCode.ORGANIZATION_MEMBER_NOT_FOUND);


        long currentTime = new Date().getTime();

        if (orgMember._getMemberState(currentTime) == OrgMemberState.BLOCKED) {
            throw new VedantuException(VedantuErrorCode.MEMBER_IS_BLOCKED);
        }
        return orgMember;

    }


    public abstract UserAuthReq authenticate(String memberId, String password ,OrgMember orgMember);
    public abstract String getMemberUsername(String orgId, String memberId) throws VedantuException;

    public abstract AddOrgMemberMappingRes addMemberMapping(AddOrgMemberMappingReq addOrgMemberMappingReq, boolean noExceptionOnExistingMapping);
}
